### ISSUE TITLE
Get-ChildItem(ls) adds newlines at the end of list elements

### ISSUE THREAD

**Issue by youkim005** [JanDeDobbeleer/oh-my-posh#1132]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Expected: 
![20211029_이미지 003](https://user-images.githubusercontent.com/83401142/139366393-b63594bf-8c2b-4cd2-b87a-23909e679fc4.png)

What Happened instead:
![image](https://user-images.githubusercontent.com/83401142/139366381-67cdfe07-094b-40c3-ac86-5e1186b46035.png)

### Version

3.180.3

### Theme

blueish

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by lnu** [comment]
Make me think of this [one](https://github.com/JanDeDobbeleer/oh-my-posh/issues/908).
The answser is [here](https://github.com/JanDeDobbeleer/oh-my-posh/issues/908#issuecomment-910173401)

**Comment by youkim005** [comment]
![image](https://user-images.githubusercontent.com/83401142/139388466-253d49ef-bb4d-434b-8a85-d98036c99f6c.png)
i have tried the solution; while it fixes the extra newline it seems to break powerline fonts;
could it be because i am using chocolatey version of oh-my-posh?

**Comment by JanDeDobbeleer** [comment]
@youkim005 the problem is that those fonts NEED a UTF-8 terminal to work (which is standard everywhere except for Windows PowerShell). They have a ticket for which they do the follow-up, but no solution yet. You might look at enabling it [system-wide](https://github.com/PowerShell/PowerShell/issues/7233#issuecomment-640243647) but I can't guarantee that will once again introduce the initial issue. This is something PowerShell needs to fix.
