### ISSUE TITLE
Newer PowerShell module (>5.16.0) requires downloads

### ISSUE THREAD

**Issue by peetrike** [JanDeDobbeleer/oh-my-posh#1382]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When updating oh-my-posh module, it didn't indicate somewhere, that executable is not any more included in module.  When module is installed to AllUsers scope and then user without root privileges tries to start the module, the download fails, as regular user is not allowed to write to module location.

The installation doc could point out that executable (and themes) are downloaded first time the module is initialized.  Additionally, it could be good to have instructions how to manually download executable and themes.

The download stores executable and themes in module root folder, not in version-specific folder.

### Theme

no themes involved

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
no logs involved
```

**Comment by JanDeDobbeleer** [comment]
@peetrike yes, this was a change which makes the module size significantly smaller. The reason we install it outside of the module version folder is so that we can overwrite it rather than keep filling the disc with unnecessary items. Can you show the error? I think we can for sure display a how to in case it fails. The best option however is to install using Winget or Scoop, then you have zero issues. PowerShell modules are a good idea for PowerShell only modules, and we've always kept the module for backwards compatibility, but it's more a hassle than a gain nowadays.

**Comment by peetrike** [comment]
The error message is not any more available but there was error from executing line https://github.com/JanDeDobbeleer/oh-my-posh/blob/4f921dbb0f94cd68757360a94b15cc51b205b305/packages/powershell/oh-my-posh.psm1#L54

and executing line https://github.com/JanDeDobbeleer/oh-my-posh/blob/4f921dbb0f94cd68757360a94b15cc51b205b305/packages/powershell/oh-my-posh.psm1#L87

Both errors appeared because non-admin user can't write to specified locations.

So if module is installed to AllUsers scope, then the module must be loaded first time by the same user who updated/installed the module.

**Comment by JanDeDobbeleer** [comment]
I can definitely catch that and display a warning that explains this.

**Comment by peetrike** [comment]
that would make much less confusion.
