### ISSUE TITLE
Theme shouldn't have background color

### ISSUE THREAD

**Issue by imba-tjd** [JanDeDobbeleer/oh-my-posh#14]
`Set-Theme lambda`:

![图片](https://user-images.githubusercontent.com/24759802/93727188-99d5ca00-fbec-11ea-8748-c05546adfdfb.png)

`Set-PoshPrompt lambda`:

![图片](https://user-images.githubusercontent.com/24759802/93727196-a22e0500-fbec-11ea-9e72-d2dafe68ed41.png)

As you can see there are two more issue in the second pic as well.

**Comment by JanDeDobbeleer** [comment]
You can easily change the background colors so they are consistent with the one in your setting, in this case using `Write-PoshTheme` to get the json, store it elsewhere, adjust the background colors and set the location of that one as your theme using `Set-PoshPrompt -Theme mytheme.json`. Although it might be interesting to make bg colors optional (I think there's a way).

The second issue is because of the font being used, in my tests I always use [MesloLGM NF](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Meslo.zip), which is why it does not show those icons correctly in your setup.

**Comment by JanDeDobbeleer** [comment]
This should now be OK! I did have to think out of the box for this one as transparent foreground text does not exist. Fortunately, you can reverse the ANSI color sequence meaning a transparent background (or one that isn't set) can become the foreground.
