### ISSUE TITLE
Modular Design

### ISSUE THREAD

**Issue by jonatandorozco** [JanDeDobbeleer/oh-my-posh#1549]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Before elaborating the issue I want to thank you for this awesome project. It's an excellent tool for the dev community and a no-brainer extension for daily use.

Currently, the application is bundling the segments in the app. There are three issues with that:

- Slow down segment's development: As segments are being added to program's codebase and the amount of segment is increasing, there will be more time for reviewing and approving all the changes made per segment
- Increased program file size and startup time: In view of the above, that will also increase the binary size as more segments are added and also when existing segments add more features increasing startup time
- Useless segments due to user needs: As we know all of us don't need all the segments provided in our daily workflow so there is no need to include them all the in the main program

My proposal is to make oh-my-posh architecture modular adding the following benefits in order to fix those issues :

- Empowering users to develop the segments by themselves. With that said, the segment development cycle is handled in another repository, by segment's creators.
- Decoupling the codebase and enabling a segment API: Providing a way to customize the segments, run the code needed to provide the info that will be showed in the segment and a settings layer (shared settings/segment settings)
- Plug & play system to select the segments you want to load and see

Taking into account that this feature will require a lot of discussion in order to know the best way to implement it, I bring this to the table without an specific way to do it in order to have your oppinion about it.

And again, thanks for all your effort on this excellent project. Hoping you can continue working on it

**Comment by JanDeDobbeleer** [comment]
That’s actually more V2’s design.

Looking at the speed optimizations together with binary size optimizations we’ve already done, I don’t necessarily see this become an issue anytime soon. It’s effortless to add a segment, and I must say we’re doing a pretty swift job at getting these merged. Only the ones that require more work, are obviously taking more time but that’s the exception rather than the rule. I guess we’ll see what time will bring, but I don’t see any valid reason to go in that direction now.

Additionally, this is written in go. There's no eval functionality (for good reason).
