### ISSUE TITLE
Version 7.37.1 is broken - Error: unknown flag: --version

### ISSUE THREAD

**Issue by kdrai007** [JanDeDobbeleer/oh-my-posh#1915]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

whenever I reload my window powershell oh-my-posh keep updating don't know why

### Theme

theme-paradox

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
Error: unknown flag: --version
Usage:
  oh-my-posh [flags]
  oh-my-posh [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  config      Interact with the configuration
  help        Help about any command
  prompt      Setup the prompt for your shell
  version     Print the version

Flags:
  -c, --config string   config (required)
  -h, --help            help for oh-my-posh
  -i, --init            init (deprecated)
  -s, --shell string    shell (deprecated)

Use "oh-my-posh [command] --help" for more information about a command.

unknown flag: --version
Updating oh-my-posh executable to 7.37.1
```

**Comment by JanDeDobbeleer** [comment]
@kdrai007 known issue which was fixed an hour ago. To resolve the issue altogether, it's best to remove oh-my-posh, then install again to the version with the fix:

```powershell
Remove-Item $env:POSH_PATH -Recurse -Force
Uninstall-Module -Name oh-my-posh -AllVersions
Install-Module -Name oh-my-posh -MinimumVersion 7.37.2
```

**Comment by kdrai007** [comment]
Thanks brother its working

**Comment by eamodio** [comment]
Any idea how long before this hits winget? As I just hit this issue now, and 7.37.2 isn't available there.

**Comment by JanDeDobbeleer** [comment]
@eamodio the PR is out there, they only need to merge it. Same for removal of this broken version. Although using winget, you can install and reload the shell. You'll see the error again when this version lands but reloading fixes it.

**Comment by angadschawla** [comment]
Did the three step you laid out above, and this happened:

`Error: unknown flag: --version
Usage:
  oh-my-posh [flags]
  oh-my-posh [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  config      Interact with the configuration
  help        Help about any command
  prompt      Setup the prompt for your shell
  version     Print the version

Flags:
  -c, --config string   config (required)
  -h, --help            help for oh-my-posh
  -i, --init            init (deprecated)
  -s, --shell string    shell (deprecated)

Use "oh-my-posh [command] --help" for more information about a command.

unknown flag: --version
Oh My Posh Error:

ReadMapCB: expect { or n, but found 4, error found in #1 byte of ...|404: Not Fo|..., bigger context ...|404: Not Found|...
Remove-Item $env:POSH_PATH -Recurse -Force
Remove-Item: Cannot bind argument to parameter 'Path' because it is null.
Oh My Posh Error:

ReadMapCB: expect { or n, but found 4, error found in #1 byte of ...|404: Not Fo|..., bigger context ...|404: Not Found|...Uninstall-Module -Name oh-my-posh -AllVersions
Uninstall-Package: No match was found for the specified search criteria and module names 'oh-my-posh'.

Oh My Posh Error:

ReadMapCB: expect { or n, but found 4, error found in #1 byte of ...|404: Not Fo|..., bigger context ...|404: Not Found|...Install-Module -Name oh-my-posh -MinimumVersion 7.37.2

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y
Oh My Posh Error:

ReadMapCB: expect { or n, but found 4, error found in #1 byte of ...|404: Not Fo|..., bigger context ...|404: Not Found|...`

**Comment by angadschawla** [comment]
Actually figured out removing it, but after new installation of 7.37.2, I get this:

oh-my-posh: C:\Users\angad\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:1
Line |
   1 |  … githubusercontent.com/JanDeDobbeleer/oh-my-posh/v$(oh-my-posh --versi …
     |                                                       ~~~~~~~~~~
     | The term 'oh-my-posh' is not recognized as a name of a cmdlet, function, script file, or executable
     | program. Check the spelling of the name, or if a path was included, verify that the path is correct
     | and try again.

oh-my-posh: C:\Users\angad\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:1
Line |
   1 |  oh-my-posh --init --shell pwsh --config https://raw.githubusercontent …
     |  ~~~~~~~~~~
     | The term 'oh-my-posh' is not recognized as a name of a cmdlet, function, script file, or executable
     | program. Check the spelling of the name, or if a path was included, verify that the path is correct
     | and try again.

**Comment by JanDeDobbeleer** [comment]
@angadschawla Did you remove the broken version first? There are steps listed [here](https://github.com/JanDeDobbeleer/oh-my-posh/issues/1915#issuecomment-1066048092)

**Comment by angadschawla** [comment]
@JanDeDobbeleer Yes I did, figured some of this out myself at this point but now I have the correct version installed but it is still not working. (sorry, new to Windows Powershell). 

PS C:\Users\angad> Get-InstalledModule

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
7.37.2               oh-my-posh                          PSGallery            A prompt theme engine for any shell

PS C:\Users\angad>

But as you can see, I don't have oh-my-posh running at the end. It was running stably before the update.

**Comment by JanDeDobbeleer** [comment]
@angadschawla can you share your `$PROFILE`?

**Comment by angadschawla** [comment]
@JanDeDobbeleer 
PS C:\Users\angad> notepad $PROFILE
This is what is in the file:
"oh-my-posh prompt init pwsh --config https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/v$(oh-my-posh --version)/themes/jandedobbeleer.omp.json | Invoke-Expression"

**Comment by angadschawla** [comment]
@JanDeDobbeleer Sorry for wasting your time! Figured it out! Just tried to import module again after restart, and it worked. Not sure what the issue was, but seems to be on my machine and not your work. Thanks again!

**Comment by JanDeDobbeleer** [comment]
@angadschawla by adding `Import-Module oh-my-posh` above the init line in your profile:

```powershell
Import-Module oh-my-posh
oh-my-posh prompt init pwsh --config https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/v$(oh-my-posh --version)/themes/jandedobbeleer.omp.json | Invoke-Expression
```

**Comment by angadschawla** [comment]
@JanDeDobbeleer Yeah, that worked! Thanks.
