### ISSUE TITLE
BATT Err using jandedobbeleer theme

### ISSUE THREAD

**Issue by Cruik** [JanDeDobbeleer/oh-my-posh#20]
Hey, 

its me again..

i'm playing around with different themes and their configuration and come along with the following behaviour..

when my notebook is plugged in and fully charged, i get the "BATT ERR", when its loading it shows the percentage in green and when its not plugged in the information is displayed in red.

is it only on my machine with the batt err ?

![grafik](https://user-images.githubusercontent.com/5699060/93917210-fb8c5600-fd0a-11ea-8e35-41c113ba3c04.png)

**Comment by JanDeDobbeleer** [comment]
@Cruik is that on Windows? I noticed this too, but on MacOS where I could reproduce it and I have a PR open with a fix on the dependency. Let's see if I can reproduce this 👍🏻

**Comment by Cruik** [comment]
Yeah its on windows, 
Sorry forget to give you this Information

**Comment by JanDeDobbeleer** [comment]
I finally was able to reproduce this, but I still need to catch the moment :-) I did not forget about this!

**Comment by rashil2000** [comment]
Can confirm this. Shows error BATT ERR whether the device is charging or discharging. Tried on PowerShell 5 with jandedobbeleer theme.

**Comment by JanDeDobbeleer** [comment]
It depends, I have a device where I've only seen it once, but it went away so fast I couldn't debug it. Hasn't happened since. So rather annoying to reproduce on my end.

**Comment by flatrick** [comment]
I'm constantly getting **BATT ERR%**, I copied the theme and removed lines for battery, but the message just won't go away, in both Windows Powershell and Powershell 7.0.3 on Windows 10.

If I change my config to point to a different pre-made theme, these works just fine, but my modified jandedobbeleer.json behaves as if the block about battery info is still there.

I've verified with Process Monitor that the application indeed is reading my config-file and not something else, but based on the behaviour, I'd guess something is wrong in my config (though I can't see it myself) and it just defaults to it's own internal default settings.

edit:
you should probably make the application print an error-message if the file is saved in the wrong codepage.. my issue was that my own config-file had been saved as UCS-2 BE BOM instead of UTF-8 😄

**Comment by JanDeDobbeleer** [comment]
Point taken, I'm going to print a NO CONFIG/INVALID CONFIG text in the standard embedded theme (which is too identical to jandedobbeleer).

**Comment by JanDeDobbeleer** [comment]
I changed the way it handles this, still seeing the error occasionally (Windows only though) but it now defaults to showing 100%. I never seem to be able to move fast enough to debug the [third party library ](https://github.com/distatus/battery)I use when it happens as it disappears within about a minute on my machine.

**Comment by JanDeDobbeleer** [comment]
Closed due to finding the use-case and having a hack in place.
