### ISSUE TITLE
Detect Volta Node.js version

### ISSUE THREAD

**Issue by charlesroper** [JanDeDobbeleer/oh-my-posh#2045]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Would it be possible to detect the version of Node associated with current project by [Volta](https://docs.volta.sh/guide/understanding#managing-your-project)?

E.g., the following screenshot shows that OMP is displaying my default node (16.14.2), yet the version I have pinned using Volta is 14.19.1. The version of Node to use is added to `package.json` by Volta.

Many thanks!

![2022-04-06_11](https://user-images.githubusercontent.com/176/161983020-5237348d-beae-41f2-993a-a0cd4029f407.png)
.

**Comment by JanDeDobbeleer** [comment]
@charlesroper this actually works on my machine? Could it be this is because of how Volta works on Windows?

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/2492783/166006948-4e507b5c-56f3-4d4a-bbaf-ccf7c543b849.png">

There's a paragraph on the Volta site:

> NOTE
Volta's functionality depends on creating symlinks, so you must either:
Enable [Developer Mode](https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development#accessing-settings-for-developers) (recommended)
Run Volta with elevated privileges (not recommended)

If you can validate the above, and in case that's done and doesn't affect the behaviour, can you tell me if the output of `volta list --current --format plain` does provide the right version info? As that means we can use that.

**Comment by charlesroper** [comment]
I just tried again, and something must have changed somewhere because it's working now. Will close this now. 😄 

![2022-05-04_02](https://user-images.githubusercontent.com/176/166605305-2395803c-b385-4e2e-b03e-7e1754046939.png)
.
