### ISSUE TITLE
Cursor location incorrect on WSL/Fish

### ISSUE THREAD

**Issue by ehawman-rosenberg** [JanDeDobbeleer/oh-my-posh#2206]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

All examples in Windows Terminal on Windows 10.

Using pwsh my prompt renders properly
![image](https://user-images.githubusercontent.com/81652082/166311274-f04f4c6b-8035-4e00-8344-5decceaa1e65.png)

Using WSL Ubuntu zsh everything is still fine:
![image](https://user-images.githubusercontent.com/81652082/166312579-8a0f699b-ac4c-4bcc-a435-c71294968357.png)

Using WSL Ubuntu fish the cursor starts embedded in the prompt (note the white line)
![image](https://user-images.githubusercontent.com/81652082/166311450-b7185cd3-8b01-4ccb-8efa-85fff6942107.png)

~~At home on my Mac, fish renders with no problems in iTerm~~*(wrong)*. Here at work I've poked around and found that adding anything to the end of the prompt (ending at [L261](https://gist.github.com/ehawman-rosenberg/fb7febbd01e19a17eb4bd55c7599cffb#L261)) just scooches the problem over to the right.

### Theme

https://gist.githubusercontent.com/ehawman-rosenberg/fb7febbd01e19a17eb4bd55c7599cffb/raw/77264b3c07379583391fa87d925902c908e0d665/devious-diamonds.omp.json

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

fish

### Log output

These are the debug files for all three.
[omp-debug-wsl-fish.txt](https://github.com/JanDeDobbeleer/oh-my-posh/files/8605602/omp-debug-wsl-fish.txt)
[omp-debug-wsl-zsh.txt](https://github.com/JanDeDobbeleer/oh-my-posh/files/8605603/omp-debug-wsl-zsh.txt)
[omp-debug-pwsh.txt](https://github.com/JanDeDobbeleer/oh-my-posh/files/8605604/omp-debug-pwsh.txt)

All three were dumped direct to file, not sure if that changes anything wrt encoding or whatnot.

**Comment by ehawman-rosenberg** [comment]
So here's something interesting,

This is on MacOS in iTerm2
<img width="473" alt="Screen Shot 2022-05-02 at 22 00 17" src="https://user-images.githubusercontent.com/81652082/166399886-fd6cdd71-bf10-4def-aa0e-cdf875c58bf1.png">

Fish prompts aren't aligning correctly on both Mac and WSL. Also note that the prompt mark from my iterm segment adamantly refuses to come down from its lofty line. I'm investigating that independently.

<img width="473" alt="Screen Shot 2022-05-02 at 22 07 03" src="https://user-images.githubusercontent.com/81652082/166400274-79349380-2187-448b-9e67-6b5b3140ba5e.png">

On the built-in Terminal fish works properly... why...

**Comment by ehawman-rosenberg** [comment]
In VSC on Windows, I'm seeing the following

![image](https://user-images.githubusercontent.com/81652082/167053622-f3c14bbc-31fa-4672-9430-b13e6c727f99.png)

![image](https://user-images.githubusercontent.com/81652082/167053632-bcb600bb-8d18-4385-9ad2-87f2d3e68fa8.png)

**Comment by lewis-yeung** [comment]
Using your [config](https://gist.githubusercontent.com/ehawman-rosenberg/fb7febbd01e19a17eb4bd55c7599cffb/raw/77264b3c07379583391fa87d925902c908e0d665/devious-diamonds.omp.json), the following are what I see in VSC v1.67.0 and PowerShell v7.2.3 on Windows:

- Non-elevated:

	![non-elevated](https://user-images.githubusercontent.com/83903009/167086392-72391e7d-4c92-4498-8e53-69a3e762f56a.png)

- Elevated:

	![elevated](https://user-images.githubusercontent.com/83903009/167086388-988b2d21-0c13-43ed-bbdd-caeaa188d6b8.png)

<details><summary>BTW</summary>

The leftmost heart shape symbol (`\uf004`) overlaps the upper left triangle symbol (`\ue0bc`). This only appears on my end and may be a difference in glyph width rendering, which is introduced by a specific Nerd Font and can be ignored.

</details>

I can occasionally reproduce the bug you describe, with a precondition though. The gaps between the prompt and the cursor in a non-elevated shell persist until I make several (2, 3 or sometimes more) continuous empty hits on Enter key and get a newly spawned prompt as the following: (note that the cursor is immediately to the right of the prompt)

![cursor-pos](https://user-images.githubusercontent.com/83903009/167086383-90d5017d-a15d-4228-8b8e-2ccc24b10ed3.png)

and the duplicate character bug is like this:

![bug](https://user-images.githubusercontent.com/83903009/167086378-4bb92110-bd14-46fb-bd16-034ca8271d55.png)

That's SO weird! 😲 But soon I got the culprit - [Zero Width Space](https://unicode-table.com/en/200B/) (`\u200b`). If I replace it with another visible character, the bug will never appear. If you are curious about this magical space character, you can copy and paste it in your VSC terminal to test how it affects the next character input and backspaces.

I understand why you need a `\u200b` and what kind of prompt you want, but we have to admit that the trick is a little hacky. ~~I'm interested in making it work correctly while for the time being I haven't found a perfect solution to get the same rendering results as the original.~~

Besides, I have tested this config in Windows Terminal and it works correctly. Well, that's not strange because VSC's integrated terminal is based on Xterm.js with completely different implementations.

**Updated:** 🆕💡 I found a workaround just now! A backspace (`\u0008`) works for this use case on my end (still a little hacky though 😄). Just replace the last two segments (`path` and `text`) as the following and have a try.

```json
{
  "background": "p:purple",
  "foreground": "p:dracula-black",
  "powerline_symbol": "\ue0bc",
  "properties": {
    "folder_icon": "\uf07b",
    "folder_separator_icon": " \uf554 ",
    "home_icon": "\uf7db",
    "max_depth": 3,
    "style": "agnoster_short"
  },
  "style": "powerline",
  "template": " \ue5ff{{ .Path }} ",
  "type": "path"
},
{
  "background": "p:purple",
  "background_templates": [
    "{{ if .Root }}p:red{{ end }}"
  ],
  "foreground": "p:dracula-white",
  "style": "diamond",
  "template": "{{ if .Root }} \uf0e7 {{ else }}\u0008{{ end }}",
  "trailing_diamond": "\ue0b0",
  "type": "text"
}
```

**NOTES:** AFAIK, this trick is not a skeleton key for the time being because it doesn't work correctly for any right-aligned segments in PowerShell. As for the reason, see #2083.

<details><summary>BTW</summary>

The last segment of type `exit` will never be rendered since the template includes only a single space character, even with `"always_enabled": true`.

```json
{
  "alignment": "left",
  "newline": true,
  "segments": [
    {
      "foreground": "p:cyan",
      "foreground_templates": ["{{ if gt .Code 0 }}#ef5350{{ end }}"],
      "properties": {
        "always_enabled": true
      },
      "style": "plain",
      "template": " ",
      "type": "exit"
    }
  ],
  "type": "prompt"
}
```

See [docs](https://ohmyposh.dev/docs/configuration/templates#hiding-segments):

> Only ***spaces*** are excluded, meaning you can still add line breaks and tabs if that is something you're after.

If you want a space to be always appended at the end, you can simply add `"final_space": true` to your config.

</details>

**Comment by ehawman-rosenberg** [comment]
@lewis-yeung You're a genius! The zero-space char was the culprit.

I honestly have no idea what I was thinking on that space-only exit segment. I think I was doing testing a while back and then forgot about it.

[This is the live one](https://gist.githubusercontent.com/ehawman-rosenberg/fb7febbd01e19a17eb4bd55c7599cffb/raw/devious-diamonds.omp.json)

I'll be submitting a fix for that char shortly. Thanks again.

@JanDeDobbeleer going forward, is `\u0008` the recommended fix or will there be another technique?

**Comment by lewis-yeung** [comment]
@ehawman-rosenberg Just in addition, you need to change this (**Line 245** of your [config](https://gist.githubusercontent.com/ehawman-rosenberg/fb7febbd01e19a17eb4bd55c7599cffb/raw/devious-diamonds.omp.json)):

```json
"template": " \ue5ff {{ .Path }}{{ if .Root }} {{ else }}\u0008{{ end }}",
```

to

```json
"template": " \ue5ff {{ .Path }} ",
```

then it works correctly, otherwise the prompt will be rendered as the following:

![last-char-got-eaten](https://user-images.githubusercontent.com/83903009/167189612-1c2cc27f-b253-4078-a126-d43a1a96379d.png)

where the last character of the CWD path is eaten by the backspace (`\u0008`). 😆

**Comment by ehawman-rosenberg** [comment]
@lewis-yeung Just a little nom lol. I think the zero-space char was a legacy item from when I was playing around with skipping the folder icon entirely.

So for L256: if .Root, renders ` \uf0e7 ` (w/ spaces on each side). Else, backspaces 1 char out of 0 (doing nothing).

So I think this actually works out well (despite being mildly hacky). If your backspace character is deleting text you care about, then you don't actually need a placeholder character. If your backspace is triggered, then you don't actually have text you care about to delete.

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg for a zero width character, we use `\u2800`. Messing with other characters can always have unwanted side effects. If we found the culprit, can we close the issue?

**Comment by ehawman-rosenberg** [comment]
@JanDeDobbeleer idk where I got `\u200b` from in the first place since that was clearly the wrong thing to use. `\u2800` it is!

**Comment by lewis-yeung** [comment]
@ehawman-rosenberg The **original Line 256** is just fine, but the **original Line 245**  needs a tweak indeed. I have tested the new live config that you posted just now, and it shows as the following in a non-elevated shell:

![extra-spaces](https://user-images.githubusercontent.com/83903009/167200473-6cac345d-4a3b-400f-ba48-ef6eaa51ef89.png)

where the extra spaces can be obtrusive, I think. Well, the tweak stuff is up to you since it's your own config. 😆 Happy coding! 🎉

**Comment by lewis-yeung** [comment]
The [Braille Pattern Blank](https://unicode-table.com/en/2800/) (`\u2800`) is not a zero width character. We use this to replace a regular space so it can be rendered even if it's the only character in a segment.

**Comment by ehawman-rosenberg** [comment]
@lewis-yeung Aha! That is indeed why I put that there. That's fixed. So `\u2800` is the cause of this unwanted space?
![image](https://user-images.githubusercontent.com/81652082/167204810-4ecb0218-8c4e-4927-ac1e-a57d5af8898d.png)

This should be 1 space.

If `\u2800` is printing actual space, then does asking for some way to render the style blocks on zero-width templates that doesn't bork formatting become a feature request?

**Comment by lewis-yeung** [comment]
@ehawman-rosenberg Yes, the `\u2800` is definitely a printable character. Besides,  using a backspace trick as is mentioned in my first comment is just fine for a left-aligned segment and brings no extra spaces.

**Comment by ehawman-rosenberg** [comment]
Ok I have it all set up with `\u0008`. This simplifies L245 significantly. gist.github.com has stopped updating for the moment, I think I was making too many changes too quickly. Anyway I'll have to remember that if we actually get a zero width character (instead of a -1 width), I'll need to revert that change. NBD.

Thanks for the assist!
