### ISSUE TITLE
$Home printed as well as ~

### ISSUE THREAD

**Issue by centreboard** [JanDeDobbeleer/oh-my-posh#24]
I think it should be replacing the text but is being printed before it. Seems to happen in all themes which print the whole path.
![image](https://user-images.githubusercontent.com/10487726/94301054-e2311700-ff61-11ea-919b-b1c26c3a9f7a.png)

**Comment by JanDeDobbeleer** [comment]
Ooh, that's a Windows issue only it seems. Will fix!

**Comment by JanDeDobbeleer** [comment]
This was a hassle to chase. Turns out that creating a non-case sensitive platform was a bad idea to begin with. There can be `c:` and `C:` pointing at the same location resulting in all kinds of funky behavior. Also, having Cygwin installed overwrites `$HOME` so there's a lot of stuff on Windows which can go wrong that shouldn't.

Once I'm done writing the documentation, I'm merging this one in as well.

**Comment by JanDeDobbeleer** [comment]
Be aware the new version is now known as Oh my Posh V3 :-)

Install-Module oh-my-posh -Scope CurrentUser -AllowPrerelease
