### ISSUE TITLE
How do I set the size of the icon? 

### ISSUE THREAD

**Issue by aaronecgberht** [JanDeDobbeleer/oh-my-posh#2445]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

How do I set the size of the icon? 
![屏幕截图 2022-06-27 165518](https://user-images.githubusercontent.com/108109787/175901905-6a638ab5-6cad-42eb-a566-360e65100344.png)

**Comment by lewis-yeung** [comment]
@aaronecgberht 😅 Unfortunately, you cannot tweak it via OMP because that's something about how your terminal app renders a Nerd Font. The only thing you can do is to use other icon characters in your theme config. It is easy to test which icons are rendered consistent in size on your end. Possibly helpful reference: [Cheat Sheet for Nerd Font](https://www.nerdfonts.com/cheat-sheet).

**Comment by aaronecgberht** [comment]
> @aaronecgberht 

😔, I want to configure the github icon, I am so "fetch_upstream_icon": true, configured, I do not know if there is another way to configure

**Comment by JanDeDobbeleer** [comment]
@aaronecgberht have a look at the segment's [docs](https://ohmyposh.dev/docs/segments/git#upstream). As @lewis-yeung states, we can't influence that.
