### ISSUE TITLE
[DBG]: prompt in powershell

### ISSUE THREAD

**Issue by graphixillusion** [JanDeDobbeleer/oh-my-posh#2502]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Since the last version, oh-my-posh will load the debug prompt, no matter which theme you have choosen.

### Theme

everything

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
.
```

**Comment by lewis-yeung** [comment]
@graphixillusion What's the output of `@((Get-PSCallStack).Location)[0]`?

**Comment by 386408003** [comment]
I have the same problem in a Simplified Chinese System.
output of @((Get-PSCallStack).Location)[0] is:
<无文件>
![QQ图片20220711105140](https://user-images.githubusercontent.com/15917855/178180003-148cdb24-9d6c-4a38-8aa5-c9ae515858f5.png)

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer This bug happens in an OS of non-English locale, which is caused by [a recent commit](https://github.com/JanDeDobbeleer/oh-my-posh/commit/27edeedeaf5cc07a50d23bc96c20540d62cc4337#diff-878b46f4ae6c1a83e8ee23b152cb60b8d8292218d8c268485633454ac42580c8R269):

https://github.com/JanDeDobbeleer/oh-my-posh/blob/27edeedeaf5cc07a50d23bc96c20540d62cc4337/src/shell/scripts/omp.ps1#L269

We have to find another solution for the debug prompt.

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung who localizes internals 😭, maybe we can regex as it's always `<text>`. I'll do a fix.
