### ISSUE TITLE
oh-my-posh prompt adjusting automatically according to the window size

### ISSUE THREAD

**Issue by RiteshChepuri** [JanDeDobbeleer/oh-my-posh#2526]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

if we adjust the window from one to other size the prompt is breaking down it would be a nice feature if the prompt automatically adjust according to the window size of the terminal.

**Comment by JanDeDobbeleer** [comment]
@RiteshChepuri this has been pitched a few times. While in certain shells you can redraw the current prompt if you're able to detect size changes, it actually requires a clear screen because the previous ones will still be wonky. That makes this a potentially annoying functionality, provided it does work.
