### ISSUE TITLE
Windows cmd render not currectly, some strange leading spaces exists

### ISSUE THREAD

**Issue by liudonghua123** [JanDeDobbeleer/oh-my-posh#2536]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I installed and configured `oh-my-posh` with cmd according to the docs on https://ohmyposh.dev/docs/installation/prompt. But I found some strange leading space when starting input commands, when I use `right` key to do completion, it seemed the strange leading space disappeared.

See the following screen recording for more details.

https://user-images.githubusercontent.com/2276718/179565135-0fb16879-915b-4843-a8b2-7ebd28b91693.mp4

I also tested on `powershell`. and it seems no problem.

![image](https://user-images.githubusercontent.com/2276718/179569405-d59ed884-57fe-4c0f-92ce-928f0a93a4ca.png)

### Theme

the default theme, installed via the docs on https://ohmyposh.dev/docs/installation/prompt.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

other (please specify)

### Log output

```Shell
 Liu.D.H   ~            oh-my-posh debug                  in cmd at 01:06:48

Version: 8.18.0

Segments:

ConsoleTitle(false) -   2 ms -
session(true)  -   1 ms -  Liu.D.H@desktop-thinkpad-ldh 
path(true)     -   3 ms -  ~
shell(true)    -   1 ms -  WindowsTerminal
text(true)     -   1 ms -  no config
exit(true)     -   4 ms -   

Run duration: 99.6352ms

Cache path: C:\Users\Liu.D.H\AppData\Local\oh-my-posh

Config path: C:\Users\Liu.D.H\"C:\Users\Liu.D.H\AppData\Local\oh-my-posh\config.omp.json"

Logs:

2022/07/19 01:06:54 debug: Getenv
C:\Users\Liu.D.H\AppData\Local
2022/07/19 01:06:54 Getenv duration: 1.0025ms, args: LOCALAPPDATA
2022/07/19 01:06:54 CachePath duration: 1.0025ms, args:
2022/07/19 01:06:54 debug: Getenv
"C:\Users\Liu.D.H\AppData\Local\oh-my-posh\config.omp.json"
2022/07/19 01:06:54 Getenv duration: 0s, args: POSH_THEME
2022/07/19 01:06:54 Shell duration: 79.6324ms, args:
2022/07/19 01:06:54 resolveConfigPath duration: 79.6324ms, args:
2022/07/19 01:06:54 Init duration: 81.633ms, args:
2022/07/19 01:06:54 Flags duration: 0s, args:
2022/07/19 01:06:54 config.loadConfig duration: 0s, args:
2022/07/19 01:06:54 Flags duration: 0s, args:
2022/07/19 01:06:54 debug: Getenv

2022/07/19 01:06:54 Getenv duration: 1.0031ms, args: OMP_CACHE_DISABLED
2022/07/19 01:06:54 WindowsRegistryKeyValue duration: 0s, args: HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\ColorizationColor
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 debug: WindowsRegistryKeyValue
ColorizationColor(DWORD): 0xC40078D4
2022/07/19 01:06:54 Root duration: 0s, args:
2022/07/19 01:06:54 Shell duration: 0s, args:
2022/07/19 01:06:54 ErrorCode duration: 0s, args:
2022/07/19 01:06:54 IsWsl duration: 0s, args:
2022/07/19 01:06:54 debug: Pwd
C:\Users\Liu.D.H
2022/07/19 01:06:54 Pwd duration: 0s, args:
2022/07/19 01:06:54 debug: Home
C:\Users\Liu.D.H
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 debug: User
Liu.D.H
2022/07/19 01:06:54 User duration: 0s, args:
2022/07/19 01:06:54 debug: Host
desktop-thinkpad-ldh
2022/07/19 01:06:54 Host duration: 0s, args:
2022/07/19 01:06:54 GOOS duration: 0s, args:
2022/07/19 01:06:54 TemplateCache duration: 1.0028ms, args:
2022/07/19 01:06:54 Flags duration: 0s, args:
2022/07/19 01:06:54 debug: Pwd
C:\Users\Liu.D.H
2022/07/19 01:06:54 Pwd duration: 0s, args:
2022/07/19 01:06:54 debug: Home
C:\Users\Liu.D.H
2022/07/19 01:06:54 GOOS duration: 0s, args:
2022/07/19 01:06:54 debug: Getenv

2022/07/19 01:06:54 Getenv duration: 0s, args: SSH_CONNECTION
2022/07/19 01:06:54 debug: Getenv

2022/07/19 01:06:54 Getenv duration: 0s, args: SSH_CLIENT
2022/07/19 01:06:54 TemplateCache duration: 0s, args:
2022/07/19 01:06:54 TemplateCache duration: 0s, args:
2022/07/19 01:06:54 Shell duration: 0s, args:
2022/07/19 01:06:54 debug: Pwd
C:\Users\Liu.D.H
2022/07/19 01:06:54 Pwd duration: 0s, args:
2022/07/19 01:06:54 debug: Home
C:\Users\Liu.D.H
2022/07/19 01:06:54 GOOS duration: 0s, args:
2022/07/19 01:06:54 debug: Pwd
C:\Users\Liu.D.H
2022/07/19 01:06:54 Pwd duration: 0s, args:
2022/07/19 01:06:54 Flags duration: 0s, args:
2022/07/19 01:06:54 debug: Pwd
C:\Users\Liu.D.H
2022/07/19 01:06:54 Pwd duration: 0s, args:
2022/07/19 01:06:54 debug: Home
C:\Users\Liu.D.H
2022/07/19 01:06:54 GOOS duration: 0s, args:
2022/07/19 01:06:54 GOOS duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 PathSeparator duration: 0s, args:
2022/07/19 01:06:54 GOOS duration: 0s, args:
2022/07/19 01:06:54 IsWsl duration: 0s, args:
2022/07/19 01:06:54 StackCount duration: 0s, args:
2022/07/19 01:06:54 DirIsWritable duration: 0s, args:
2022/07/19 01:06:54 TemplateCache duration: 0s, args:
2022/07/19 01:06:54 TemplateCache duration: 0s, args:
2022/07/19 01:06:54 Shell duration: 0s, args:
2022/07/19 01:06:54 debug: Pwd
C:\Users\Liu.D.H
2022/07/19 01:06:54 Pwd duration: 0s, args:
2022/07/19 01:06:54 debug: Home
C:\Users\Liu.D.H
2022/07/19 01:06:54 GOOS duration: 0s, args:
2022/07/19 01:06:54 Shell duration: 0s, args:
2022/07/19 01:06:54 Flags duration: 0s, args:
2022/07/19 01:06:54 TemplateCache duration: 0s, args:
2022/07/19 01:06:54 TemplateCache duration: 0s, args:
2022/07/19 01:06:54 Shell duration: 0s, args:
2022/07/19 01:06:54 debug: Pwd
C:\Users\Liu.D.H
2022/07/19 01:06:54 Pwd duration: 0s, args:
2022/07/19 01:06:54 debug: Home
C:\Users\Liu.D.H
2022/07/19 01:06:54 GOOS duration: 0s, args:
2022/07/19 01:06:54 TemplateCache duration: 0s, args:
2022/07/19 01:06:54 TemplateCache duration: 0s, args:
2022/07/19 01:06:54 Shell duration: 0s, args:
2022/07/19 01:06:54 debug: Pwd
C:\Users\Liu.D.H
2022/07/19 01:06:54 Pwd duration: 0s, args:
2022/07/19 01:06:54 debug: Home
C:\Users\Liu.D.H
2022/07/19 01:06:54 GOOS duration: 0s, args:
2022/07/19 01:06:54 ErrorCode duration: 0s, args:
2022/07/19 01:06:54 TemplateCache duration: 0s, args:
2022/07/19 01:06:54 TemplateCache duration: 0s, args:
2022/07/19 01:06:54 Shell duration: 0s, args:
2022/07/19 01:06:54 TemplateCache duration: 0s, args:
2022/07/19 01:06:54 debug: Getenv
C:\Users\Liu.D.H\AppData\Local
2022/07/19 01:06:54 Getenv duration: 0s, args: LOCALAPPDATA
2022/07/19 01:06:54 CachePath duration: 253µs, args:
2022/07/19 01:06:54 Flags duration: 0s, args:

 Liu.D.H   ~                                              in cmd at 01:06:58
```

**Comment by liudonghua123** [comment]
I updated the clink to the latest version, the theme seems changed a lot, it's now no config, and the strange leading spaces were disappeared.

![image](https://user-images.githubusercontent.com/2276718/179571059-54f83a41-245a-436b-ac8a-7d9c26f39f5d.png)

But when I tried to specify a theme via add `--config "C:/Program Files (x86)/oh-my-posh/themes/jandedobbeleer.omp.json"` to the `%localappdata%/clink/oh-my-posh.lua`. The strange leading spaces were still there.

![image](https://user-images.githubusercontent.com/2276718/179572497-edfa75bb-c4a5-4c39-a802-43d036311115.png)

**Comment by JanDeDobbeleer** [comment]
@liudonghua123 this is the first time this bug is mentioned so I'll have a look tomorrow 👀

**Comment by lewis-yeung** [comment]
Something similar happens with tooltips. Extra spaces appear when I press <kbd>Space</kbd> which triggers rendering a tooltip, and the first **three** characters cannot be deleted. So weird! It even happens when I press <kbd>↑</kbd> or <kbd>↓</kbd> to navigate in the command history. However, the bug only appears if I open a CMD (Command Prompt) directly, and never in a CMD entered from PowerShell.

https://user-images.githubusercontent.com/83903009/179647597-4966253a-39a5-44a2-b194-e23457408e55.mp4

BTW, I have set Windows Terminal as the default terminal app.

**Comment by liudonghua123** [comment]
I tried to open cmd in powershell, and it was the same. When I enter a space, the leading spaces disappeared, but the position of cursor did not change.

![image](https://user-images.githubusercontent.com/2276718/179675995-4b284069-c3ea-42ad-828e-6c3e618f3ef2.png)

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung the only thing I can think of is that the behaviour changed and we no longer have to add a space when the user adds a space (we do [this](https://github.com/JanDeDobbeleer/oh-my-posh/blob/a6e9a3561b77c655cac964c993d2afbea9968c66/src/shell/scripts/omp.lua#L204) for tooltips).

**Comment by JanDeDobbeleer** [comment]
@liudonghua123 @lewis-yeung I'm still on `Clink v1.3.9.2e99f4` where I can't reproduce this at all, same goes for the latest version. @chrisant996 any idea as to what's going on?

**Comment by chrisant996** [comment]
@liudonghua123 @lewis-yeung @JanDeDobbeleer 

**Some Background Information:**

This is almost always caused by a combination of Chinese locale (or sometimes Japanese or Korean), the font being used, and the characters being displayed.  The Chinese locale defines certain Unicode characters as different widths than in other locales.  In addition, each font may define the actual widths of characters differently than the "standard" widths (the problem is the "standard" is not consistent).  And so programs can't know how wide characters will actually be when displayed.  And some fonts define some characters as being one size, but provide glyphs that are a different size.

Also, the issues often show up differently in different terminals and different programs, because of slightly different rendering code and slightly different strategies for displaying characters.  Bash (and Clink) use the Readline library, which has complex code designed for old VT terminals from decades ago, and it tries to move the cursor by printing the minimum number of bytes, trying to improve display speed when rendering over a 1200 baud modem connection.  It also skips printing a character again if it knows that the character is already displayed in the corresponding cell in the terminal screen.  That's why the displayed results are sometimes especially confusing -- when actual rendered positions match calculated positions, then you won't notice those little optimizations -- but when rendered positions don't match calculated positions, then those optimizations can appear to scramble the display.  But it's really just because of the mismatch between "standard" character widths, the character widths defined in a particular font, and the actual glyph width for those characters in the font.  What a mess, right?

But those usually result in things being off by 1 or 2 spaces.

**What About This Situation?**

The situation here is off by a large number of spaces.  That's unusual, and there might be additional issues happening.

Try this:
1. `clink set debug.log_terminal true`
2. Start a new Clink session.
3. Reproduce the problem a few times (maybe 3, for example).
4. The `clink.log` file in the profile directory will contain a detailed log of all characters that were output, including ANSI escape codes.
5. Upload the `clink.log` file here.

I have a Lua script I can use to replay the log on my own terminal screen.  Then we can see whether there is something wrong in the characters that are being output, or if there is a problem in Clink itself, or if the issues are just due to CJK character width mismatches.

**Comment by lewis-yeung** [comment]
> This is almost always caused by a combination of Chinese locale (or sometimes Japanese or Korean), the font being used, and the characters being displayed.

@chrisant996 You're right! In a directly opened CMD, after I changed the code page from "Chinese Simplified (GB2312)" (ID: 936) to "Unicode (UTF-8)" using `chcp 65001`, the bug didn't appear. @JanDeDobbeleer And now I know why the bug cannot be reproduced on your end. :)

I have uploaded two log files of a buggy case and a normal one. It seems that they differ in setting the cursor position by ANSI sequence `CSI n G` (Cursor Horizontal Absolute).

[buggy.log](https://github.com/JanDeDobbeleer/oh-my-posh/files/9161662/buggy.log)
[normal.log](https://github.com/JanDeDobbeleer/oh-my-posh/files/9161664/normal.log)

**Comment by chrisant996** [comment]
@lewis-yeung Yes, that confirms it, for the issue you're experiencing.

There's nothing that the oh-my-posh or Clink programs can do to help, unfortunately.
The choices are:
1. Change the codepage.
2. Change which characters are displayed, or change the prompt configuration.
3. Change the font (changing the font might help, or it might not).

@liudonghua123 I realized that in your case, the left side of the prompt has many characters, and that is probably the issue. 
 The character width discrepancies add up, and cause the issue.  Your choices are the same as above.

It is interesting that PowerShell doesn't experience the problem ... but I expect PowerShell doesn't have the optimizations for old VT terminals and low bandwidth/high latency dialup connections.  PowerShell probably just prints the prompt text each time, to position the cursor.  And so, probably you'll experience strange issues when the input line wraps when it reaches the right edge of the terminal.  That is where the mismatched width calculations should become visible in PowerShell.

**Comment by JanDeDobbeleer** [comment]
@chrisant996 thanks for confirming. Closing this one as we can't resolve it.

**Comment by liudonghua123** [comment]
@chrisant996 @JanDeDobbeleer Thanks for the explanation, I tested with `chcp 65001` and it did not have such problems.
