### ISSUE TITLE
Display avaliavle themes without powershell

### ISSUE THREAD

**Issue by senge-dev** [JanDeDobbeleer/oh-my-posh#2615]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hello, I am a Linux user in China, I have switched from powerlevel10k to oh-my-posh, because your theme is very beautiful and powerful. but I want to display all avaliable themes without install powershell, can you update oh-my-posh script and add a parameter to display all themes?

**Comment by JanDeDobbeleer** [comment]
@senge-studio not doing this as we have the previews in the docs and the PowerShell function is a legacy feature. You could easily create a for loop to go through all files as in Linux we have now way to know if/where you downloaded all themes. Only on Windows we know this which is why we have that functionality in PowerShell.
