### ISSUE TITLE
VPN slows down oh-my-posh

### ISSUE THREAD

**Issue by KAEYL98** [JanDeDobbeleer/oh-my-posh#2693]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Whenever connected to a VPN without broad internet access, oh-my-posh slows down considerably trying to do HTTP requests.

Not sure if this can be resolved by some configuration on my end

### Theme

default.omp.json

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

bash

### Log output

```Shell
2022/08/23 16:06:13 Getenv duration: 984ns, args: XDG_CACHE_HOME
2022/08/23 16:06:13 CachePath duration: 12.443µs, args:
2022/08/23 16:06:13 debug: HTTPRequest
GET /JanDeDobbeleer/oh-my-posh/v8.30.0/themes/default.omp.json HTTP/1.1
Host: raw.githubusercontent.com
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


2022/08/23 16:06:18 error: HTTPRequest
Get "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/v8.30.0/themes/default.omp.json": context deadline exceeded
2022/08/23 16:06:18 HTTPRequest duration: 5.001174465s, args: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/v8.30.0/themes/default.omp.json
2022/08/23 16:06:18 downloadConfig duration: 5.00119964s, args: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/v8.30.0/themes/default.omp.json
2022/08/23 16:06:18 resolveConfigPath duration: 5.001212116s, args:
2022/08/23 16:06:18 Init duration: 5.002458515s, args:
2022/08/23 16:06:18 Flags duration: 72ns, args:
2022/08/23 16:06:18 config.loadConfig duration: 20.498µs, args:
2022/08/23 16:06:18 Flags duration: 41ns, args:
2022/08/23 16:06:18 debug: Getenv
```

**Comment by JanDeDobbeleer** [comment]
@KAEYL98 you can set the config locally as when using the initialization without `--config` parameter, it will download the default config from the repo which seems to fail due to a bad connection. 

The fix? Download the [config](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/default.omp.json) locally and reference it directly. This will also allow you to tweak it to your liking at the same time. See the [prompt](https://ohmyposh.dev/docs/installation/prompt) section for more information.

**Comment by KAEYL98** [comment]
thanks setting the config fixed it
