### ISSUE TITLE
conda env name didn't showing up

### ISSUE THREAD

**Issue by lucasjinreal** [JanDeDobbeleer/oh-my-posh#2789]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug happened!

![Uploading image.png…]()

### Theme

oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH/kushal.omp.json" | Invoke-Expression

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH/kushal.omp.json" | Invoke-Expression
```

**Comment by lucasjinreal** [comment]
![image](https://user-images.githubusercontent.com/21303438/190196968-4f82afc3-2f0f-44e7-8365-29442081a41d.png)

**Comment by JanDeDobbeleer** [comment]
@jinfagang ~~can you provide the log output? It's needed as otherwise there's no way to help you (as it's 99.99% a configuration issue).~~

Scratch the above, that [theme](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/kushal.omp.json) doesn't have a [Python](https://ohmyposh.dev/docs/segments/python) configuration so it's normal it doesn't show up. If you like that one, [tweak it](https://ohmyposh.dev/docs/installation/customize) so it includes a Python segment.

**Comment by lucasjinreal** [comment]
@JanDeDobbeleer thanks! I am a DL worker, it's widely used conda in python expecially on windows, does there a out-of-box theme can use conda promot?

**Comment by JanDeDobbeleer** [comment]
@jinfagang atomic, aliens, agnoster, atomicBit, bubbles, ...
