### ISSUE TITLE
Prompt right default space

### ISSUE THREAD

**Issue by jabed-web-dev** [JanDeDobbeleer/oh-my-posh#2888]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Prompt right space, terminal padding, and scroll. They combine to form a large space on the right. It looks ugly.
![image](https://user-images.githubusercontent.com/59810760/194051705-bac3ed3e-69b5-4561-86d1-2faa40646cb9.png)

**Comment by jabed-web-dev** [comment]
I think this space should not be there by default

**Comment by JanDeDobbeleer** [comment]
@jabed-dev can I get your theme config?

**Comment by jabed-web-dev** [comment]
https://gist.github.com/jabed-dev/3dd3accf72524ab8e0c6fda84f51fe67

**Comment by JanDeDobbeleer** [comment]
@jabed-dev this doesn't happen for me. So either make sure oh-my-posh is up-to-date or have a look at what else could be causing this (terminal, scripts). But it works perfectly here (the 1 character offset is due to icons, as they can influence the actual rendering).

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/2492783/194077546-a5b595e0-127d-4c6d-8601-b615873e61f4.png">
