### ISSUE TITLE
Ruby segment shouldn't show `NO VERSION`

### ISSUE THREAD

**Issue by ffes** [JanDeDobbeleer/oh-my-posh#3031]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

At the moment the Ruby segment shows `NO VERSION` when it can't find Ruby, but the node and dotnet segment don't do that. I find the `NO VERSION` a bit annoying and not really helpful.

![image](https://user-images.githubusercontent.com/3225656/198965752-d9abcaad-f4a2-4720-9b75-5bb0e511a808.png)

I only "use" Ruby to build my Jekyll-based websites in a Docker container, so I don't have any need to install Ruby locally. And I do the same for dotnet and node, although I use dotnet mostly on my Windows machine.

Is there a way for me to disable the `NO VERSION` text in the Ruby segment? And if you might introduce that text to other segments as well, please use the same option there as well.

**Comment by ffes** [comment]
Just noticed that the Angular segment says `cannot get version` when `npm install` hasn't been run yet. A sort of similar situation.

**Comment by JanDeDobbeleer** [comment]
@ffes yes, this is by design. You can adjust the template easily as that's the `.Error` property which is shown. Removing that from the template (and any conditional logic) will also remove that.

This is implemented by request of multiple users, so a design feature and the default template reflects that. But, it's easily adjusted.
