### ISSUE TITLE
App not work

### ISSUE THREAD

**Issue by p6002** [JanDeDobbeleer/oh-my-posh#3194]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

So i install app and font following this site:
https://ohmyposh.dev/docs/installation/windows
But there is missing information how to start it. My windows terminal is stll black.

**Comment by p6002** [comment]
Okay, never mind. It stops working on ssh connection, so it's not for me. 
For the future, I recommend making a regular exe file that will fire up powershell with an overlay.

**Comment by JanDeDobbeleer** [comment]
@p6002 I want to make sure I understand your request. You want oh-my-posh to run PowerShell for you? We're not a shell so that's a definitive no.

On the page you referenced we have the next step listed, and setting up your prompt which works cross shell, is one of those. What needs to be adjusted to clarify that's not an optional step?
