### ISSUE TITLE
Remove first newline on start and clear when `"newline": true`

### ISSUE THREAD

**Issue by CodeF53** [JanDeDobbeleer/oh-my-posh#3388]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

With a theme that has `"newline": true` in the first block, there will be a leading newline when starting the terminal and when running `clear`
![image](https://user-images.githubusercontent.com/37855219/213928189-10378a69-2190-43cc-9390-4d36a1ea85d8.png)
![image](https://user-images.githubusercontent.com/37855219/213928261-18b309f8-5138-4a9d-9c30-14bdc75b68eb.png)
Ideally, newlines would be ignored in these cases.

**Comment by CodeF53** [comment]
I apologize if this is a duplicate, searching issues for `is:issue "newline": true` gave 124 closed issues, and I couldn't look through them all.

**Comment by JanDeDobbeleer** [comment]
@CodeF53 I'm working on this as we speak.

**Comment by mbs-c** [comment]
I just upgraded to 13.6.0 and I do not think the second part of this bug is fixed properly: The initial prompt now omits the extra newline, but the unwanted newline after `clear` is still present in both versions of PowerShell.

**Comment by JanDeDobbeleer** [comment]
@mbs-c Clear isn't something we capture. It moves everything to the top of the screen, not sure if there's a low impact way to see if we're on the first line that's also fool proof.

This isn't a bug either, it's just behavior.

**Comment by mbs-c** [comment]
@JanDeDobbeleer
I can imagine it's hard to capture, I just wanted to point out that the initial description mentions `clear` as well and that this part hasn't changed. Personally, the behavior after `clear` even bothers me more than the behavior on initial load, because I didn't mind the newline after all the verbose PowerShell messages as much.

You're also absolutely right that this isn't a "bug" per se, but rather a feature request. Personally, I am trying to re-create powerlevel10k's behavior, which only shows a newline before the prompt if there's a transient prompt from a previous command on the screen, and that does not seem to be possible at the moment.

**Edit**: I am basically halfway there with the following configuration that's supposed to mimic a single-line powerlevel10k prompt:
```js
{
  // [snip]
  "blocks": [
    {
      "newline": true,
      "segments": [
        // [snip] long prompt configuration
      ],
      "type": "prompt"
    },
    {
      "alignment": "right",
      "segments": [
        // [snip] long rprompt configuration
      ],
      "type": "rprompt"
    }
  ],
  "transient_prompt": {
    "background": "transparent",
    "foreground": "#0f0",
    "foreground_templates": [
      "{{ if gt .Code 0 }}#f00{{ end }}"
    ],
    "template": "\u276f "
  }
}
```

If the newline after `clear` was skipped, then this would replicate powerlevel10k's behavior perfectly.

**Comment by CodeF53** [comment]
Maybe a new issue should be made for the clear feature request.

**Comment by JanDeDobbeleer** [comment]
I can first have a look at if it's possible, because having a feature request that can't be handled for most shells would be rather annoying.

**Comment by JanDeDobbeleer** [comment]
@CodeF53 @mbs-c give me tomorrow to make sure I didn't do anything stupid but here you go. Already works in bash, zsh and pwsh.

https://user-images.githubusercontent.com/2492783/214122540-5d53bd4b-b8b5-4392-805d-9ad0ef57ff7f.mov
