### ISSUE TITLE
Proper documentation needed!

### ISSUE THREAD

**Issue by p6002** [JanDeDobbeleer/oh-my-posh#3558]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Does anyone have instructions on how to use this? Because the official documentation is kind of a colorful joke. 
I tried a year ago with identical results, following the documentation each time. 
Is it such a complicated process that it can't be contained in a few lines of code to be pasted, so that at least the basic demo version can work? 

https://i.ibb.co/d4G4JGp/2023-03-05-215758.png

**Comment by JanDeDobbeleer** [comment]
@p6002 I'm assuming you're asking on how to install and configure a font? Because that's something that's different per OS and terminal. As far as font installation goes, we have beta functionality available using `oh-my-posh font install`, and for configuration, have a look at your terminal's documentation.

That said, this kind of disrespect is not something I tolerate, so feel free to either create a PR and make it less of a joke, or use any other tool out there.

**Comment by p6002** [comment]
How do I remove it now? In general, this documentation leads to a point where the user has a broken terminal with no clear way back.

I'm not surprised that the project on github has no issue since everything is closed at the beginning.

**Comment by kapsiR** [comment]
@p6002 I have to write a few words here just because of your tone! 

1. **Please think about how you communicate online**, even if something bothers you!
2. Jan serves this (very popular) project in his spare time and does a pretty neat job! (He is one of the [GitHub Stars][gh-star] because of that!)
3. He is very inclusive and tries to help out when he can, that shows of his good character


Regarding your question:
 - How did you install it in the first place? (You can undo what you did and the prompt is back to default)

[gh-star]: https://stars.github.com/profiles/jandedobbeleer/

**Comment by JanDeDobbeleer** [comment]
For future reference, @p6002 is blocked for multiple violations of the Code of Conduct. I don't need these insults in my life.
