### ISSUE TITLE
Prompt changes using tab completion with PS-GuiCompletion

### ISSUE THREAD

**Issue by thorstenkampe** [JanDeDobbeleer/oh-my-posh#365]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Prompt changes using tab completion with PS-GuiCompletion or PowerTab

### Environment

- Oh my Posh version: 3.78.1
- Theme: none
- Operating System: Windows 10
- Shell: PowerShell 7.1.1
- Terminal: ConEmu

### Steps to Reproduce

1. Invoke tab completion with PS-GuiCompletion or PowerTab (for instance with `cd <tab>`
![image](https://user-images.githubusercontent.com/475462/105319499-3b821d80-5bc5-11eb-85c4-218345dd3270.png)

2. move cursor down (or any other key)

3. PowerLine symbol inverts its colors
![image](https://user-images.githubusercontent.com/475462/105319557-55bbfb80-5bc5-11eb-96d6-fd4abf3d8e8b.png)

**Expected behavior:**
Prompt should not change

**Actual behavior:**
Prompt changes

Config:
```json
{
    "final_space": true,
    "blocks": [
        {
            "type": "prompt",
            "alignment": "left",
            "segments": [
                {
                    "type": "shell",
                    "style": "powerline",
                    "powerline_symbol": "",
                    "foreground": "lightWhite",
                    "background": "lightBlue"
                }
            ]
        }
    ]
}
```

**Comment by JanDeDobbeleer** [comment]
@thorstenkampe I'll see if I can reproduce this in other terminals. That said, this is going to be a bug in either ConEmu, PS-GuiCompletion or PowerTab as once rendered, there's nothing oh-my-posh can do that affects the visualisation. This is however an inverted ANSI sequence, and one of the tools is going to ruin the rendering when it draws that completion box.

**Comment by thorstenkampe** [comment]
I opened the issue here because the problem does not occur in my Starship prompt (although that might be coincedental).

**Comment by JanDeDobbeleer** [comment]
@thorstenkampe confirmed to be a bug with the toolset rather than oh-my-posh. It even changes the colours on the screen meaning their rendering influences the drawn ANSI characters. The default `Install-Module` progress bar also has this issue in Powershell meaning it could be something low level in the standard toolset. However, there's nothing I can do to resolve that, our string is drawn correctly and the tool(s) simply re-render that part and ruin it. So it's up to them to fix it.

This doesn't happen with every color and impacts background colours primarily. That's probably also why you don't see this on starship, when I use a prompt with only foreground colours, this doesn't happen.
