### ISSUE TITLE
Make NerdFont installation in user-scope, not admin

### ISSUE THREAD

**Issue by Kenya-West** [JanDeDobbeleer/oh-my-posh#3945]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Windows Settings app now allows installing font without UAC elevation (Windows 10 latest version and Windows 11). Fonts are installed by user scope.

Could the same be done by OhMyPosh?

**Comment by JanDeDobbeleer** [comment]
@Kenya-West that's possible, BUT, the reason we install as admin is because fonts don't always show up (or work correctly) when not installed system wide. That's why we do this.

That said, I can explore adding that flag, bug it will void any warranty 😅

**Comment by joey-ma-steelgem** [comment]
I really appreciate this tool, but I'm also having some difficulty installing this particular theme in a Windows environment. I think there may be 2 parts to my situation, but it is related to the author's post. I'd really appreciate any help!

First. Without installing Nerd Fonts, I'm seeing some squares in my terminal, specifically, I'd like to apply the [`bubbles` theme](https://ohmyposh.dev/docs/themes#bubbles). I am assuming that I'm seeing squares instead of appropriate icons is because I don't have the correct fonts installed.

Then, following the instructions from [docs/installation/fonts](https://ohmyposh.dev/docs/installation/fonts), entering `oh-my-posh font install`, I am getting:

```
You need to be admin to install a font on Windows
```

But when I enter `oh-my-posh font install` when running Terminal as administrator, I am getting 

```
oh-my-posh : The term 'oh-my-posh' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ oh-my-posh font install
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (oh-my-posh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

The way I'm confident about adding something to `PATH` is Window's via `Edit the system environment variables` GUI window, but I'd usually locate where the app is installed to add it to `PATH`. For this "app", I'm not sure and haven't seen it from the docs where it's installed, so I don't really know how to add to PATH to resolve the last error message. 

On first loading Windows Terminal (running as administrator), I'm also getting a related error message, probably because of the `.PowerShell_profile` is now including `oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\bubbles.omp.json" | Invoke-Expression`:   

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/133689354/2e5a5343-0615-4379-a5ba-2f290a7d33fe)

So... in a way, I can see this being a feature request, but I also think there just might be something that I'm missing so that this particular feature request is not actually required. Again, appreciate any feedback! @JanDeDobbeleer

**Comment by JanDeDobbeleer** [comment]
@joey-ma-steelgem you can temporarily add something to the PATH using PowerShell too. If you want to know the actual path, without being admin, use (`Get-Command oh-my-posh).Source`, then you can add that location to the PATH on admin using `$env:Path = 'C:/Users/location/of/ohmyposh/executable/folder;' + $env:Path`

All of these questions are more related to PowerShell and PATH on Windows than oh-my-posh. Oh-my-posh installs as user unless specified otherwise so you won't have the executable on your PATH as admin in that case.

**Comment by joey-ma-steelgem** [comment]
@JanDeDobbeleer Thanks so much! 😍 That is really cool and super helpful. How do I know which font to install for the `bubbles` theme, though? I tried installing `Symbols only Nerd Font` and `Cascadia Code` and made `Cascadia Code` the default font (via Settings GUI, not `settings.json` though), but am not seeing the changes when I close and open a new Terminal. 🤔

**Comment by JanDeDobbeleer** [comment]
@joey-ma-steelgem you can pick any of the Nerd Fonts normally. Just make sure you configure the correct font name (not necessarily the same as the font file name).

**Comment by joey-ma-steelgem** [comment]
> @joey-ma-steelgem you can pick any of the Nerd Fonts normally. Just make sure you configure the correct font name (not necessarily the same as the font file name).

So I thought if I installed `CascadiaCode` from the drop down `Select font`, it would've worked. It did not. But by choosing `CaskaydiaCove Nerd Font` however worked! Thanks so much!
