### ISSUE TITLE
feat: Segment color based on context

### ISSUE THREAD

**Issue by andrewsav-bt** [JanDeDobbeleer/oh-my-posh#397]
This may be a long shot, but I'd like to change the colour of the `kubectl` segment based on which context is current. E.g for "production" it will be red, for "staging" yellow and for "test" green. Since context names will be different for different installations, the mapping needs to be configurable. It does not have to be limited to background colour either, sometimes foreground colour change could be more desirable.  It seems to me that in v2 with powershell themes there were quite a bit more flexibility here. 

How do I achieve the above?

Is it worth to include more built-in support for that? May be even not just for `kubectl`?

**Comment by JanDeDobbeleer** [comment]
That should be possible yes. I'm just wondering how to do this on an architectural level. When it came to V2, you needed to know how to write Powershell, that need is gone in V3, obviously opening other issues when it comes to low level customisation like this. But we can facilitate that for sure. Contextual background color is that hardest as foreground can be achieved using color overrides within the template. I'll let this sync in, but definitely something that could benefit more people.

**Comment by tradiff** [comment]
For what it's worth, I actually did experiment with that exact thing while developing the kubectl segment.  It can be accomplished using the template and [oh-my-posh's color support](https://ohmyposh.dev/docs/configure#colors). This example makes the namespace turn red if it's "ingress" otherwise it will be the normal color.  Combining two micro-languages like this is a bit ugly, but doable 😄 

```text
{{.Context}} :: {{if eq .Namespace \"ingress\"}}<#ff0000>ingress</>{{else if .Namespace}}{{.Namespace}}{{else}}default{{end}}
```

**Comment by JanDeDobbeleer** [comment]
@TravisTX yup, but that only works for foreground colors. The bg can be set but it's not going to be used on the entire segment.

**Comment by tradiff** [comment]
That would sound like a bug with the ascii color handling, no?  But also, I'm not able to repro what you said.

```json
{
  "type": "kubectl",
  "style": "plain",
  "foreground": "#ffffff",
  "background": "#CB4B16",
  "properties": {
    "prefix": "",
    "template": "<#00ff00,#333333>{{.Context}}</> :: {{if eq .Namespace \"ingress\"}}<#ff0000,#ffffff>ingress</>{{else if .Namespace}}{{.Namespace}}{{else}}default{{end}}"
  }
},
```

![image](https://user-images.githubusercontent.com/934490/107656101-0eafac00-6c41-11eb-9583-8b8726753e46.png)

---

edit: I just realized you were saying you want the entire segment to be changed? I show that can be done too:

```json
{
  "type": "kubectl",
  "style": "plain",
  "foreground": "#ffffff",
  "properties": {
    "prefix": "",
    "template": "{{if eq .Namespace \"ingress\"}}<#ff0000,#ffffff>{{end}}{{.Context}} :: {{if .Namespace}}{{.Namespace}}{{else}}default{{end}}{{if eq .Namespace \"ingress\"}}</>{{end}}"
  }
},

```

![image](https://user-images.githubusercontent.com/934490/107656787-bdec8300-6c41-11eb-99a2-ba7c818112fd.png)

**Comment by JanDeDobbeleer** [comment]
@TravisTX try powerline

**Comment by tradiff** [comment]
Gotcha, the powerline symbols don't get affected.  Maybe use the go template syntax in `background` and `foreground` properties, with a custom domain object representing the segment.

So you could do something like this:
```
"background": "{{if contains \"production\" .Text }}#FF0000{{else}}#00FF00{{end}}"
```

Note: `contains` isn't a normal part of go's templates, but there [are libraries](https://github.com/Masterminds/sprig) that add that type of thing.

**Comment by JanDeDobbeleer** [comment]
That's an interesting approach!

**Comment by andrewsav-bt** [comment]
Go templates are appealing because they are immediately available but if we think about the examples above they are quire unwieldy. Additionally the fact that the format of configuration is `json` (sic!) means no multi-lines and also rigid escape rules, which exacerbates the problem.

How about this:

```json
"background": [
  "{{if contains \"PrOdUcTiOn\" .Text }}#FF0000{{end}}",
  "{{if contains \"staging\" .Text }}#00FF00{{end}}",
  "#0000FF"
 ]
```
First non-empty result will be chosen. The goal it to make it a bit easier to read and write.

**Comment by andrewsav-bt** [comment]
Compare with yaml:

```yaml
background: 
- '{{if contains "PrOdUcTiOn" .Text }}#FF0000{{end}}'
- '{{if contains "staging" .Text }}#00FF00{{end}}'
- '#0000FF'
```

**Comment by JanDeDobbeleer** [comment]
@TravisTX sprig support has been added.

Based on the conversation, I propose to do the following:

- introduce a new general `Property` to `properties.go`  called `color_templates`. That one can contain the array as [described](https://github.com/JanDeDobbeleer/oh-my-posh3/issues/397#issuecomment-777997728) by @andrewsav-bt 
- extend `Segment` with the ability to get its colours (`foreground` and `background`) rather than call the properties directly. The presence of `color_templates` in combination with `color_background` can indicate which color needs to be returned in either case. As always, `color_background ` is optional and should fallback to `false`. If no template returns a value, the value set in either `background` or `foreground` is used.

**Comment by tradiff** [comment]
I agree that when possible, what's easiest for the user should win. And @andrewsav-bt 's array example is definitely easier to read.

Is it possible to allow the `background` and `foreground` properties to be either a string or an array? This would allow users to opt in to the array syntax without breaking backwards compatibility with a simple string, and also avoid having to create a possibly confusing separate property and override logic for the same logical property.

To do this, we would change the `background` property to a type of `interface{}`. At runtime, inspect the value to determine whether it's a string or an array of strings (or some exception case).  I haven't tried this, but I don't immediately see any reason it couldn't be done. (disclaimer: I'm pretty new to go, so apologies if this was all nonsense)

Just a thought.

**Comment by jerkovicl** [comment]
> That would sound like a bug with the ascii color handling, no? But also, I'm not able to repro what you said.
> 
> 
> {
>   "type": "kubectl",
>   "style": "plain",
>   "foreground": "#ffffff",
>   "background": "#CB4B16",
>   "properties": {
>     "prefix": "",
>     "template": "<#00ff00,#333333>{{.Context}}</> :: {{if eq .Namespace \"ingress\"}}<#ff0000,#ffffff>ingress</>{{else if .Namespace}}{{.Namespace}}{{else}}default{{end}}"
>   }
> },
> ![image](https://user-images.githubusercontent.com/934490/107656101-0eafac00-6c41-11eb-9583-8b8726753e46.png)
> 
> edit: I just realized you were saying you want the entire segment to be changed? I show that can be done too:
> 
> 
> {
>   "type": "kubectl",
>   "style": "plain",
>   "foreground": "#ffffff",
>   "properties": {
>     "prefix": "",
>     "template": "{{if eq .Namespace \"ingress\"}}<#ff0000,#ffffff>{{end}}{{.Context}} :: {{if .Namespace}}{{.Namespace}}{{else}}default{{end}}{{if eq .Namespace \"ingress\"}}</>{{end}}"
>   }
> },
> ![image](https://user-images.githubusercontent.com/934490/107656787-bdec8300-6c41-11eb-99a2-ba7c818112fd.png)

@TravisTX  how did you put prompt on the next line after all the segments?

**Comment by tradiff** [comment]
@jerkovicl Here's my full theme:  [travis.omp.json](https://gist.github.com/TravisTX/26db681962dd28698cd7aa8f934d357c)
The [newline block](https://ohmyposh.dev/docs/configure#block) on line 79 followed by a separate block for the `>` character is how you achieve that.

**Comment by JanDeDobbeleer** [comment]
> Is it possible to allow the `background` and `foreground` properties to be either a string or an array?

I would not do that, make it explicit. It can be done, so your idea is doable, but it's architecturally not the right path (in my opinion).

**Comment by jerkovicl** [comment]
@TravisTX gotcha i didn't know newline can be a separate block in v3. Thx alot

**Comment by AndrewSav** [comment]
It may be a little bit harder to program, with regards to json deserialization, but the same property can accept either string (simple cases) or array - more complex ones. To me introducing a new property for this makes it more complex to use.

**Edit**: sorry did not read the entire thread:

> Is it possible to allow the background and foreground properties to be either a string or an array? This would allow users to opt in to the array syntax without breaking backwards compatibility with a simple string, and also avoid having to create a possibly confusing separate property and override logic for the same logical property.

I support this.

> I would not do that, make it explicit. It can be done, so your idea is doable, but it's architecturally not the right path (in my opinion).

Do you think this because you prioritize developer/architect convenience (more straight forward code, no messy parts) to user convenience (easier to read syntax, less things to care about, put either string or array in, it just works) ?

If not, could you explain a bit more why this does not feel right?

**Comment by JanDeDobbeleer** [comment]
@AndrewSav from an implementation point of view it doesn't really matter. From a user perspective, you need to also know the details on which properties are at your disposal, meaning if you accept templates on a higher level in the same property, you still need to get the details in the segment you'd apply it to. Most people won't need this, meaning the complexity (and even info) shouldn't be on that level, background is what it is, a color (which already accepts named and hex values). When going in detail on that specific part it will confuse people (that’s my experience) and my opinion is that it goed against proper modeling. The use case is different and it’s easier to check for existence of a value rather than do type checks all over the place because “we can” and feel smart about it (I know, that’s heavily opinionated on my end, but also there, my experience has something to do with that).

**Comment by AndrewSav** [comment]
@JanDeDobbeleer 

> if you accept templates on a higher level in the same property, you still need to get the details in the segment you'd apply it to.

Sorry, I did not understand this part. Could you please reword/clarify? What levels are we talking about here? Json? Higher level than what, than a segment? Which details in the segment you still need and how does it play into user experience? Apologies again, just confused here.


>  background is what it is, a color (which already accepts named and hex values)

I may be missing something, but it will keep working this way for a `string`. So should be no change from what it is now.

> I know, that’s heavily opinionated on my end, but also there, my experience has something to do with that

I also value experience a lot, because it's clearly superior to guessing and theorizing. However it does happen that different people have different experience in similar situations. 

Same property:

```json
"background": [
  "{{if contains \"PrOdUcTiOn\" .Text }}#FF0000{{end}}",
  "{{if contains \"staging\" .Text }}#00FF00{{end}}",
  "#0000FF"
 ]
"foreground": [
  "{{if contains \"PrOdUcTiOn\" .Text }}#00FF00{{end}}",
  "{{if contains \"staging\" .Text }}#0000FF{{end}}",
  "#FF0000"
 ]
```
Different  property:

```json
"foreground":"#FF0000"
"background":"#00FF00"
 "properties": {
    "color_background": true,
    "color_templates": [
      "{{if contains \"PrOdUcTiOn\" .Text }}#FF0000{{end}}",
      "{{if contains \"staging\" .Text }}#00FF00{{end}}"
    ]
}
```

It looks like if we are using additional properties:

- We cannot change foreground and background at the same time
- When `color_templates` is used, and is written so that it never returns an empty value, the "higher level" `foreground` or `background` properties won't be used at all, which I find confusing - e.g. you put anything in them at all and it will not matter. There is no good way to detect if on some input a template returns a empty value, so we cannot even issue a warning in this case. Yet if you _omit_ `foreground` or `background` (even if it's not used) the whole segment is affected (unless further code changes)

Finally, and this is not directly related to this issue, I would like to understand which properties go to top level segment and which go inside the "properties" collection. Currently the line is blurred to me, I might have missed a point about that in the [documentation](https://ohmyposh.dev/docs/configure#properties). Also, is there a need to separate them like this? Is there a hard and fast rule when adding a new property if it goes to the properties collection or to segment's top level?

**Comment by JanDeDobbeleer** [comment]
Now we're getting somewhere. Cool. You've effectively convinced me to try this path because indeed, you can't have a ruleset for foreground/background simultaneously. I'll do it. That does mean we deprecate `color_background` and the way git colors currently work (and others).

**Comment by JanDeDobbeleer** [comment]
> Sorry, I did not understand this part. Could you please reword/clarify?

I was talking about documentation. I know this confuses people A LOT and the more information you share on a basic level, the more issues I will get because of it ;-)

**Comment by AndrewSav** [comment]
Documentation confuses people? ;)

**Comment by JanDeDobbeleer** [comment]
Too much information at once confuses people. So if you have a property that can do X, but also Y, it tends get confusing. Especially when we're talking advanced use cases.

**Comment by JanDeDobbeleer** [comment]
This is going to take a while as I have to change A LOT

**Comment by tradiff** [comment]
@JanDeDobbeleer  I just looked at your branch.  It looks like you're removing the context specific color properties from segments such as battery and git. Is there a way to reproduce that with the templates? Are you thinking it would be too confusing to leave them in place? I feel like they could be left as they were, as long as the documentation is explicit on the weight.

BTW if you're overwhelmed, I don't mind helping out. I could even work on documentation 😄

**Comment by JanDeDobbeleer** [comment]
@TravisTX they become obsolete when using the templates as the logic should be in there. I'm even thinking of doing that plus adding required templates to all segments and deprecate prefix and icons for example. But all of this implies V4 😅

**Comment by JanDeDobbeleer** [comment]
I'm going to do this differently. I stand by my refactor but that's pushing it too far. It does give me a perfect vision of what V4 should be. I'll explain a new approach later today 😂

**Comment by JanDeDobbeleer** [comment]
@AndrewSav @TravisTX final proposal in my PR. The reasoning behind this is that to add it to the color itself, we effectively remove the need for setting the color in the segment as that can all be handled by the template. Same goes for Segment templates which deprecate the need for prefix/icons/booleans. I like the idea, but that would imply V4, which is ok as the idea has been in my head for a couple of months, but for the sake of this ticket, that's out of scope. I'd love to create V4 with those features and remove a whole lot of logic ;-)

**Comment by JanDeDobbeleer** [comment]
@AndrewSav @TravisTX incoming, works like a charm. I'm still going to deprecate the git and battery colours and work from there (mark them as deprecated).

**Comment by AndrewSav** [comment]
> @TravisTX they become obsolete when using the templates as the logic should be in there. I'm even thinking of doing that plus adding required templates to all segments and deprecate prefix and icons for example. But all of this implies V4 😅

Not everyone wants to learn go templates, this makes prefix and icons useful.

**Comment by JanDeDobbeleer** [comment]
> Not everyone wants to learn go templates

True, maybe there's a neat middle ground. That's something I'll learn when working on it.

**Comment by JanDeDobbeleer** [comment]
@AndrewSav this feature is available, docs have been added so I will close this.

**Comment by AndrewSav** [comment]
@JanDeDobbeleer  Hey, sorry I just got around to test this, working perfectly thank you for implementing (and helping to design @TravisTX ) this! Working very well!
