### ISSUE TITLE
Turn folder_format into folder_template

### ISSUE THREAD

**Issue by Destroy666x** [JanDeDobbeleer/oh-my-posh#4226]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Would be great if `folder_format` was instead turned into `folder_template` supporting `{{ }}` template syntax. That could then have vars like:
- `{{ .FolderName }}` - just what `%s` currently is, so either regular name or mapped name/icon 
- `{{ .FolderLocation }}` - raw path to that folder

Why? The main reason would be to link each subdir separately with `{{ path .FolderName .FolderLocation }}` template function to open parent folders quickly.

Similar treatment could be then done to `edge_format` for consistency.

**Comment by JanDeDobbeleer** [comment]
@Destroy666x ~~allowing templates here won't be very efficient. It's easier to have a switch for this that will do this for you (e.g. `folder_links`) and keep the formats as is.~~

EDIT: I have a rough draft ready but it will only work in the `full` folder style. We don't have access to the actual location, only formatted folder names which we loop to stylise. Due to that, I don't feel like adding the feature as it's rather crippled as the rework needed can't be justified on anyone's spare time.

**Comment by Destroy666x** [comment]
Oh, too bad

**Comment by Destroy666x** [comment]
@JanDeDobbeleer I consider submitting a PR for this maybe some day as this would be very helpful for some of my workflows and the changes don't look too bad to me (except tests which I haven't looked at yet maybe). Would this generally be something you'd accept if it was done well (just so I don't waste time)?

**Comment by JanDeDobbeleer** [comment]
@Destroy666x obviously. PR's are always welcome 🙏🏻
