### ISSUE TITLE
Default configuration shows a Python error

### ISSUE THREAD

**Issue by Gh0s7** [JanDeDobbeleer/oh-my-posh#423]
### Prerequisites

- [ ] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

I've just completed the basic install guide, but I'm getting the following error:

![image](https://user-images.githubusercontent.com/3979059/108044762-f7a6fa80-7042-11eb-876c-9125206e30cc.png)

(also, note the missing glyphs even if I have set `"fontFace": "Cascadia Code PL"` in my Windows Terminal's settings.
### Environment

- Oh my Posh version: `oh-my-posh: The term 'oh-my-posh' is not recognized as a name of a cmdlet, function, script file, or executable program.` (this is even weirder, as the module has been imported)
- Theme: (added the entire profile)
```
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt -Theme Paradox
```
- Operating System: Windows 2004 (19041.746)
- Shell: PowerShell 7.2.0-preview.3
- Terminal: Windows Terminal

### Steps to Reproduce

1. `Install-Module posh-git -Scope CurrentUser`
2. `Install-Module oh-my-posh -Scope CurrentUser`
3. `Install-Module -Name PSReadLine -AllowPrerelease -Scope CurrentUser -Force -SkipPublisherCheck`
4. Add the following lines to `$PROFILE`
```
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt -Theme Paradox
```
5. `. $PROFILE`
6. BONUS: With `Get-PoshThemes`, basically every theme has some kind of issue

**Comment by JanDeDobbeleer** [comment]
@Gh0s7 Cascadia Code PL has the downside of not having all font icons like [Nerd Font](https://www.nerdfonts.com) does (which is what we support ever since V2).

`oh-my-posh --version` is not supported in the module, that's for the binary only. You can use `(Get-Module oh-my-posh).Version.ToString()`

About the issue, that string is added when we can fetch the version information from what the `python` executable returns. You can either check the output of `python2 --version` or `python --version` so we can have a look at why the output is different from what we expect, or maybe you don't have Python installed and you should adjust the theme to match your needs. More information on that can be found [here](https://ohmyposh.dev/docs/installation#change-the-theme).

About the BONUS, the themes are added as samples rather than to-be used themes. Experience learned people have custom needs, which is why the need for this rework was present.

**Comment by JanDeDobbeleer** [comment]
@Gh0s7 noticed we show this error when the command returns an empty string (I have no idea how that's even possible). That's fixed in the latest release.

**Comment by Gh0s7** [comment]
Nice, at least my issue was useful somehow :)
I found another theme that works fine, so feel free to close it if you solved the main issue.
