### ISSUE TITLE
Project segment:  Follow PEP 621 to retrieve project metadata from pyproject.toml

### ISSUE THREAD

**Issue by jacobo-diaz** [JanDeDobbeleer/oh-my-posh#4461]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Template properties retrieved from pyproject.toml should follow [PEP621](https://peps.python.org/pep-0621/#table-name) and [PyPA specification](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/). 

Maybe a "Python" project type could be added to the .Type property, which could read the .Name and .Version fields from the "[project]" table in pyproject.toml.

**Comment by babieiev** [comment]
It seems like a good idea, but this new `Python` project type will conflict with `Poetry`. I don't use Poetry, but if I understand everything correctly, it has had a problem with not being PEP 621 compliant for a long time. They seem to be planning to implement PEP 621 support (at least that's what their roadmap says), but so far it looks like they haven't made much progress.

Here's my idea: maybe we could not add a separate `Python` project type, but rename `Poetry`. Then, if the name and version in the `pyproject.toml` are listed under the `[tool.poetry]` header (i.e. they exist and are not empty), extract them, and otherwise, if they are listed under the `[project]` header, get them from there.
At least, that's the best solution I've found so far.

**Comment by babieiev** [comment]
@jacobo-diaz tomorrow night I'll have some free time, so I can try to implement this feature

**Comment by jacobo-diaz** [comment]
I completely agree with you, @oleksbabieiev. Two types is confusing. Much better renaming.

Thanks a lot, 

> It seems like a good idea, but this new `Python` project type will conflict with `Poetry`. I don't use Poetry, but if I understand everything correctly, it has had a problem with not being PEP 621 compliant for a long time. They seem to be planning to implement PEP 621 support (at least that's what their roadmap says), but so far it looks like they haven't made much progress.
> 
> Here's my idea: maybe we could not add a separate `Python` project type, but rename `Poetry`. Then, if the name and version in the `pyproject.toml` are listed under the `[tool.poetry]` header (i.e. they exist and are not empty), extract them, and otherwise, if they are listed under the `[project]` header, get them from there. At least, that's the best solution I've found so far.

**Comment by JanDeDobbeleer** [comment]
@jacobo-diaz @oleksbabieiev this is a feature for the `project` [segment](https://ohmyposh.dev/docs/segments/project) BTW.
