### ISSUE TITLE
scoop install creates an oh-my-posh-wsl.ps1 which is not useful in WSL

### ISSUE THREAD

**Issue by jetersen** [JanDeDobbeleer/oh-my-posh#449]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

seems scoop does not provide a proper shim I suspect it wants `.exe` in the `bin` section to create application shim rather than a ps1 shim. I slightly remember something about being able to configuring bin for scoop.

### Environment

- Oh my Posh version: 3.96.0
- Theme: custom theme based on JanDeDobbeleer (will add it to my dotfiles later)
- Operating System: Windows 10/Ubuntu 2004 (WSL)
- Shell: zsh/pwsh
- Terminal: Windows Terminal

### Steps to Reproduce

```
scoop install https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/oh-my-posh.json
```

**Comment by JanDeDobbeleer** [comment]
Wait, you're telling me it installs the unix binary as `oh-my-posh-wsl.ps1`?

**Comment by jetersen** [comment]
nah it creates a .ps1 file with the following content:
```powershell
if (!(Test-Path Variable:PSScriptRoot)) { $PSScriptRoot = Split-Path $MyInvocation.MyCommand.Path -Parent }
$path = join-path "$psscriptroot" "..\apps\oh-my-posh\current\oh-my-posh-wsl"
if($myinvocation.expectingInput) { $input | & $path  @args } else { & $path  @args }
```
```
ll

    Directory:  C:\Users\joseph\scoop\shims

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---        25/10/2020     10.43     7,50KB 7z.exe
-a---        24/02/2021     09.21      260   7z.ps1
-a---        24/02/2021     09.21       55   7z.shim
-a---        24/02/2021     09.21      274   oh-my-posh-wsl.ps1
-a---        25/10/2020     10.43     7,50KB oh-my-posh.exe
-a---        24/02/2021     09.21      274   oh-my-posh.ps1
-a---        24/02/2021     09.21       69   oh-my-posh.shim
-a---        24/02/2021     09.20      117   scoop
-a---        24/02/2021     09.20      340   scoop.cmd
-a---        24/02/2021     09.20      268   scoop.ps1
```

**Comment by JanDeDobbeleer** [comment]
@jetersen seems to work now (at least adding to PATH)

**Comment by jetersen** [comment]
🚀 Thanks for the quick fix once again!

**Comment by glucas** [comment]
Hm, I had oh-my-posh3 installed via scoop from the default[ main bucket](https://github.com/ScoopInstaller/Main/blob/82a2206b1d50572f6bbb0dcaa374cf83397a3ff3/bucket/oh-my-posh3.json) and it had been working fine until this change. Now it fails to update. I guess that is an issue for that repo, however. 

I filed https://github.com/ScoopInstaller/Main/issues/1866 since I assume other folks like myself might find oh-my-posh via that default bucket.

**Comment by Lucky-Loek** [comment]
This update breaks my installation, since the `oh-my-posh.exe` can't be found anymore. The executable isn't copied to Scoop's `shims` directory anymore, and the update doesn't add this repo's `bin` folder to my path either. Fixing it is easy enough (just add it to the path manually), but I imagine this not being desired behavior?

**Error**
![image](https://user-images.githubusercontent.com/9716643/109120711-94098500-7746-11eb-8063-0b493f4ba278.png)

**Shims folder**
![image](https://user-images.githubusercontent.com/9716643/109120499-50af1680-7746-11eb-8f28-1cc850669a6f.png)

**User env**
![image](https://user-images.githubusercontent.com/9716643/109120607-750af300-7746-11eb-8b07-d7eac0055d80.png)

**System env**
![image](https://user-images.githubusercontent.com/9716643/109120648-8227e200-7746-11eb-81c4-e786f39f8c8a.png)

**Comment by jetersen** [comment]
scoop should add it to your path.
Try uninstalling and reinstalling with scoop.
![image](https://user-images.githubusercontent.com/1661688/109120926-e0ed5b80-7746-11eb-8406-97c26e4afb40.png)

**Comment by Lucky-Loek** [comment]
I know, but it doesn't on my machine 😜 Reinstalling does not work either. I'll add it manually and see what happens with the next update. If that still breaks, I'll create a new issue and dive in a bit deeper.

**Comment by JanDeDobbeleer** [comment]
@Lucky-Loek it did add it to my PATH when testing. Had to reboot though for it to show up.

**Comment by Lucky-Loek** [comment]
Oooh ofc, that makes sense. It's still Windows so PATH changes need a reboot.. Thanks for the quick reply! (and the awesome tool!)

**Comment by glucas** [comment]
FWIW installing via the scoop main bucket worked find for me once the issue I mentioned above was resolved. That bucket's manifest still creates shims and did not require rebooting.

**Comment by jetersen** [comment]
shims are undesirable for the `oh-my-posh-wsl` binary which is also not covered by the manifest in the main bucket... 😉
