### ISSUE TITLE
zash theme unknown symbol f119

### ISSUE THREAD

**Issue by ulvido** [JanDeDobbeleer/oh-my-posh#4528]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

questionmark symbol display error on nu shell. f119

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/27722274/e0673514-af7b-463d-9916-651b96cd51e8)

**Proposition:** \ufe56 works fine.

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/27722274/821cb6a0-fd72-4f43-9c71-619a9518fabd)

### Theme

zash

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

nu

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@ulvido this works on my machine, so that could imply your font doesn't support the character (not a V3 Nerd Font), or is a plain font. You can always adjust the theme to reflect your preferences/setup.

<img width="640" alt="image" src="https://github.com/JanDeDobbeleer/oh-my-posh/assets/2492783/fd6c2f60-5b75-490b-b584-da4cc3b1ede0">
