### ISSUE TITLE
What would be required to implement Transient Prompt in bash?

### ISSUE THREAD

**Issue by sql-sith** [JanDeDobbeleer/oh-my-posh#4550]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hi! This isn't a feature request so much as me wondering if I want to dive into a problem that I probably don't want to. :)

I just saw in https://github.com/JanDeDobbeleer/oh-my-posh/issues/2409 that transient prompt support was "not possible" in `bash` as of June 2022. 

"Not possible" caught my attention. Sometimes "not possible" is literally true, but sometimes it is a stand-in for something else, like "not possible in the same way it's done for the other shells" or "ridiculously difficult given the small benefit," etc. I suspect this is a case where "not possible" does not literally mean "impossible."

May I ask what it specific limitation is in bash that makes this problematic? I know I can read the code, but I believe in talking to people first. That frequently gives me a better idea of whether something's a good match for me or not. Thanks!

**Comment by JanDeDobbeleer** [comment]
@sql-sith the problem is that bash doesn't have native built-in `reset-prompt` and `accept-line` functions like zsh does for example. You can hook into `enter` and provide a function that executes logic, but without those abilities, there's no way to reload the prompt with a different one. There are implementations like [readline_proxy](https://github.com/axiros/readline_proxy/blob/master/readline_proxy), but those can break on upgrades so it's not a structural solution. Until bash' readline decides to create said helper functions, this is a no-go. My assumption is that this wil never happen.
