### ISSUE TITLE
activating venv of python causes the line end to go to next line

### ISSUE THREAD

**Issue by Ad-Shaikh** [JanDeDobbeleer/oh-my-posh#4672]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

hello,

I am using the themes of Ohmyposh that's inside my gist. And using CasKaydia Code NF when activating the venv inside Powershell  the line. It was perfect until i used the latest version on my other PC tried everything but couldn't find a solution so i thought let me try updating Ohmyposh on the working pc and voila it broke here tooo

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/54195531/f49508b3-99d7-4622-a62c-2b44243f3d93)

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/54195531/a6f6676d-aec1-471f-84a8-c5627e16870f)

### Theme

https://gist.github.com/Ad-Shaikh/d860871430e778aaad68a02cc9e9f71b

all other things are the same

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
Im new so no idea how to generate the logs
```

**Comment by JanDeDobbeleer** [comment]
@Ad-Shaikh you need to disable the built-in prompt hijacking by the python activation script and use oh-my-posh to display that data. We can't calculate the correct width if they prepend data AFTER us.

**Comment by Ad-Shaikh** [comment]
> @Ad-Shaikh you need to disable the built-in prompt hijacking by the python activation script and use oh-my-posh to display that data. We can't calculate the correct width if they prepend data AFTER us.

can u tell me where to change that? I am bit new I copied the theme from a YT guide

Also how was it working in older versions?

**Comment by JanDeDobbeleer** [comment]
@Ad-Shaikh we changed the logic for right aligned blocks to use spaces instead of ANSI for consistency. That's why it's now pushed.

You can set `$Env:VIRTUAL_ENV_DISABLE_PROMPT = $false` to avoid the prompt being hijacked by the script.

Check if the configuration for oh-my-posh has a Python segment and adjust if needed to include the virtual environment information.

**Comment by abceleung** [comment]
> > @Ad-Shaikh you need to disable the built-in prompt hijacking by the python activation script and use oh-my-posh to display that data. We can't calculate the correct width if they prepend data AFTER us.
> 
> can u tell me where to change that? I am bit new I copied the theme from a YT guide
> 
> Also how was it working in older versions?

I just stumbled upon this issue. Here is how I solve it:

1. Create a copy of the `.omp.json` file you like from [here](https://ohmyposh.dev/docs/themes) to somewhere in your PC (e.g. in `$HOME`)
2. Run `notepad $PROFILE` in a shell. Edit the file so that it looks like this:
```
# Replace "$HOME/powerlevel10k_rainbow.omp.json" to wherever you put your .omp.json file
oh-my-posh init pwsh --config "$HOME/powerlevel10k_rainbow.omp.json" | Invoke-Expression

# Add this line if you haven't
$Env:VIRTUAL_ENV_DISABLE_PROMPT = $false 
```
3. Launch your shell and activate a Python virtual environment. If you see your virtual environment information, then we are done.
4. If not, open the `.omp.json` file you copied with a notepad. Search for `"type": "python"`. Mine looks like this:
```
{
          "background": "#FFDE57",
          "foreground": "#111111",
          "invert_powerline": true,
          "powerline_symbol": "\ue0b2",
          "properties": {
            "display_mode": "files",
            "fetch_virtual_env": false
          },
          "style": "powerline",
          "template": " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} \ue235 ",
          "type": "python"
},
```
5. Set `"fetch_virtual_env"` to `true`.
6. Modify `"template"` so it includes `{{ .Venv }}`,
e.g. `"template": " {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} \ue235 "`

You should read the [document](https://ohmyposh.dev/docs/segments/python) for more information.
