### ISSUE TITLE
amd64 builds for msys_nt are not available for Oh My Posh

### ISSUE THREAD

**Issue by oleksis** [JanDeDobbeleer/oh-my-posh#4705]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

amd64 builds for msys_nt-10.0-26010

![Oh-My-Posh-2024-02-21_134013](https://github.com/JanDeDobbeleer/oh-my-posh/assets/44526468/41fbb130-f155-44b7-8592-2ddcc5da2eec)

**Comment by JanDeDobbeleer** [comment]
@oleksis ~~what's that? Is this you trying to install using git bash?~~ Confirmed to be git bash. This isn't supported and I will not support it as git bash is on my "Low effort" list due to being a unix emulator instead of an actual, correctly integrated platform shell. You need to use PowerShell and `Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://ohmyposh.dev/install.ps1'))`
