### ISSUE TITLE
SSH Segment or SSH handling in Session

### ISSUE THREAD

**Issue by nwykes** [JanDeDobbeleer/oh-my-posh#48]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

I'd like to add some special handling if detected running in an ssh session.

Would an ssh specific segment be best for this? Or would some properties on the hostname in the session segment be more appropriate.  I'm thinking like ssh-foreground, ssh-background, ssh-icon.

### Environment

- Oh my Posh version: 3.11.2
- Theme: all
- Operating System: all
- Shell: all
- Terminal: all

**Comment by JanDeDobbeleer** [comment]
> properties on the hostname in the session segment

I would opt for that as well. It's part of your session. Not sure of we should have color overrides specifically although It could make sense for foreground rather than background (might get messy and as soon as you're allowing partly overrides for all the colors a separate segment makes more sense imho).

If we make a `ssh-separator` we can display it as `jan@machine on sshcontext` for example with ` on ` set as that text.

**Comment by JanDeDobbeleer** [comment]
<img width="683" alt="Screenshot 2020-11-03 at 20 16 04" src="https://user-images.githubusercontent.com/2492783/98030669-aa937580-1e11-11eb-8cbb-9ab7acf5e537.png">

**Comment by nwykes** [comment]
Thanks!
