### ISSUE TITLE
VS Code terminal displays ANSI escape sequence characters

### ISSUE THREAD

**Issue by sander-struijk** [JanDeDobbeleer/oh-my-posh#4927]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/96832608/c4b3cf33-9821-47e3-885a-b5653ccc552a)

In the screenshot, I have pressed enter twice without writing any characters to the terminal and the last line is untouched.

I don't know what is wrong and how to get it fixed, I guess this is the wrong place for this, maybe it's VS Code specific but I don't know where else to turn...

### Theme

default

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
@sander-struijk Try disabling vscode's shell integrations and enable oh-my-posh' native shell integrations from the configuration.See [here](https://ohmyposh.dev/docs/configuration/general#general-settings) for more information.

**Comment by Fydon** [comment]
@sander-struijk To fix the issue you may want to include the [manual installation](https://code.visualstudio.com/docs/terminal/shell-integration#_manual-installation) of the vscode shell integration in [your profile](https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.2) `if ($env:TERM_PROGRAM -eq "vscode") { . "$(code --locate-shell-integration-path pwsh)" }` or otherwise disable the vscode shell integration (`terminal.integrated.shellIntegration.enabled`).

**Comment by sander-struijk** [comment]
Thank you @JanDeDobbeleer and @Fydon for your help, I managed to make it work with @Fydon's suggestion. Tho a note, I hade to make it the first line in my PS profile and not the last for it to work...

**Comment by Fydon** [comment]
As per #4897, the latest vscode insider build has been fixed, so the workaround is no longer needed.
