### ISSUE TITLE
I can't load my  theme

### ISSUE THREAD

**Issue by thirteenthree** [JanDeDobbeleer/oh-my-posh#626]
the version has been changed many times. You have updated the function name, file name and path. Why don't you update the configuration description,the old configuration manual has brought me a huge trouble.
whatever the path of themes is ~/Documents/WindowsPowerShell/PoshThems/ or ~/Documents/WindowsPowerShell/Modules/oh-my-posh/3.134.0/themes, I have tried two different paths putting my theme file named mytheme.psm1.however it didn't work

**Comment by lnu** [comment]
I understand the frustration but how do you think someone working for free on his spare time will get this?
Describe your problem(terminal, shell, ...) correctly and someone will try to help you.
By the way, the doc can probably be improved, so feel free to do so.

**Comment by JanDeDobbeleer** [comment]
@thirteenthree allow me to answer some of the questions. V3 is entirely new, that's why the major number got bumped, just like back in the day for V2. V3 brings some requested changes we couldn't do before and therefore the configuration changed from `.psm1` to a new config file format (json, yaml or toml), meaning your personal V2 theme will need to be ported to work on V3. The cmdlets were renamed to no longer conflict with other modules. I don't understand what you mean with "why don't you update the configuration description" as there has never been an elaborate [configuration guide](https://ohmyposh.dev/docs/upgrading) as we have right now.

**Comment by thirteenthree** [comment]
Thank you for your reply. I understand . I am using V3 version, but I refered to some configuration instructions of V2, which made me think that *. psm1 is a custom theme file of V3 (now I understand, this is V2 version); these misunderstandings are due to the  oh-my-posh2's readme.md , configuration description of the file  name readme.md does need to be updated(This is why I said "why don't you update the configuration description,becasue I  have been referring to [this](https://github.com/JanDeDobbeleer/oh-my-posh2#readme)). I have to say it is friendly for us to use json to configure, I like it.

**Comment by JanDeDobbeleer** [comment]
@thirteenthree the V2 repository is archived and renamed. Even when coming from a blog that mentions V2 you should end up on V3 as the repo name changed and V3 has the repo name V2 always used.
