### ISSUE TITLE
[PowerShell 7] Az.Accounts module is loaded even if a theme doesn't contain Azure blocks

### ISSUE THREAD

**Issue by joshtransient** [JanDeDobbeleer/oh-my-posh#642]
### Prerequisites

- [X] I have read and understand the `CONTRIBUTING` guide
- [X] I looked for duplicate issues before submitting this one

### Description

I load a theme that doesn't contain Azure or Azure Functions blocks, and the Az.Accounts module loads regardless. With PowerShell 7+, this prevents loading any other module that relies on a different version of MSAL.NET to do authentication. Can a check be added to only load Az.Accounts if a theme uses it?

### Environment

- Oh my Posh version: 3.133.0
- Theme: any
- Operating System: Windows 10 20H2
- Shell: PowerShell 7.1.3
- Terminal: any (tried in pwsh.exe and Windows Terminal)

### Steps to Reproduce

1. Open PowerShell -noprofile
2. `Import-Module oh-my-posh`
3. Try to `Import-Module` any module that uses MSAL.NET (e.g. [MSAL.PS](https://www.powershellgallery.com/packages/MSAL.PS/)
4. Receive error "Import-Module: Assembly with same name is already loaded"

**Expected behavior:** No error message

**Actual behavior:** Error message from step (4) above

**Comment by JanDeDobbeleer** [comment]
@joshtransient I don't want to open the jar of parsing the config in Powershell. You can however set `$env:AZ_ENABLED=$false` to avoid the module being loaded.

**Comment by JanDeDobbeleer** [comment]
@joshtransient any update on your end?

**Comment by joshtransient** [comment]
Env variable works. I'll close it

**Comment by gibwar** [comment]
Ended up coming to the same conclusion, for some reason, `Get-AzContext` takes 1 to 3 seconds to run and it was absolutely killing performance and driving me insane (thinking the Git perf issues came back). If we don't want to open the can of worms (which I understand), can we add something to the install docs mentioning that, if you have the Az module installed and you do not use the Az segment, it'd be worth your time to disable support?

**Comment by JanDeDobbeleer** [comment]
@gibwar where would you look for that information?

**Comment by gibwar** [comment]
I was originally thinking on the [pwsh](https://ohmyposh.dev/docs/pwsh) section, but that may be too narrow, since I guess it _could_ happen on other platforms (though I only use pwsh on Windows). Since I know there have been issues past with outdated Git versions and slowness and whatnot, maybe a troubleshooting page may be beneficial?

Putting it on the Azure segment wouldn't make sense, since I am not using it, I wouldn't have looked there. The way I ended up identifying the cause was originally wrapping the `prompt` function with stopwatch calls to see the 3s lag, then running `Write-PoshDebug` was about 100ms (on a Git repo), and eventually added `Set-PSDebug -Trace 2` to see the calls inside `Initialize-ModuleSupport` where the delay occurred.

https://github.com/JanDeDobbeleer/oh-my-posh/blob/016d981baa73629daae1ebd97db55b92a68657b5/src/init/omp.ps1#L39-L48

**Comment by JanDeDobbeleer** [comment]
@gibwar FAQ section coming
