### ISSUE TITLE
Prompt isn't showing python virtual environment.

### ISSUE THREAD

**Issue by adityamwagh** [JanDeDobbeleer/oh-my-posh#706]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

The space theme isn't showing virtual environments in the prompt.

### Environment

- Oh my Posh version: 3.146.0
- Theme: All themes
- Operating System: WSl Arch and WSL Ubuntu
- Shell: zsh
- Terminal: Windows Terminal

### Steps to Reproduce

1. Set the theme to any theme
2. Create a virtual environment using `virtualenv .env`
3. Activate using `source .env/bin/activate` 

**Expected behavior:** Show which virtual environment I am in.

**Actual behavior:** No difference in prompt.

**Comment by JanDeDobbeleer** [comment]
@adityamwagh does your theme/config have a Python segment? If so, can you share the configuration?

**Comment by adityamwagh** [comment]
This is the content of the python segment. According to the documentation, `display_virtual_env` defaults to `true`. So not mentioning it shouldn't be an issue.

```json
{
  "type": "python",
  "style": "powerline",
  "foreground": "#906cff",
  "properties": {
    "prefix": "\u005b\uE235 ",
    "postfix": "\u005D "
  }
},
```

**Comment by JanDeDobbeleer** [comment]
@adityamwagh we look at a few environment variables to define if there's a virtual env active. Can you confirm one of these actually holds a value:

- VIRTUAL_ENV
- CONDA_ENV_PATH
- CONDA_DEFAULT_ENV
- PYENV_VERSION

Also, there need to be python files in the folder to actually show the context in this basic use-case. Otherwise you need to add `"display_mode": "context"` to the segment's properties.

**Comment by adityamwagh** [comment]
> Also, there need to be python files in the folder to actually show the context in this basic use-case. Otherwise you need to add `"display_mode": "context"` to the segment's properties.

Found the culprit. Thanks!
