### ISSUE TITLE
UNABLE TO OPEN CONFIG after upgrading to oh-my-posh 3

### ISSUE THREAD

**Issue by leniel** [JanDeDobbeleer/oh-my-posh#715]
### Prerequisites

- [ X ] I have read and understand the `CONTRIBUTING` guide
- [ X ] I looked for duplicate issues before submitting this one

### Description

Getting this "Unable to open config" on the command line...

This is my PROFILE content:

```
Import-Module oh-my-posh
Set-PoshPrompt -Theme jandedobbeleer
```

### Environment

- Oh my Posh version: V 3.149.0
- Theme: jandedobbeleer
- Operating System: Win 10 21H1 (OS Build 19043.985)
- Shell:  PowerShell 7.1.3
- Terminal: Windows Terminal Preview 1.8.1032.0

### Steps to Reproduce

Opening the Windows Terminal with this custom command:

```
C:\Users\leniel\AppData\Local\Microsoft\WindowsApps\wt.exe nt -d C:\Path\Folder\Project1 --tabColor #FFB6C1; nt -d C:\Path\Folder\Project2 --tabColor #00B2EE; nt -d C:\Path\Folder\Project3
```

works but then I see at the end "UNABLE TO OPEN CONFIG" as shown in the following screenshot... I was using V2 without a problem. Not sure what's going on.

![image](https://user-images.githubusercontent.com/764854/118333161-a8595480-b4e1-11eb-844c-b2b573afd789.png)

**Expected behavior:** No message informing Unable to open config.

**Actual behavior:** Unable to open config message is showing on the command line.

**Comment by JanDeDobbeleer** [comment]
Hmm. That shouldn't happen. Can it be your terminal (ow Windows) encoding doesn't default to UTF8?

**Comment by JanDeDobbeleer** [comment]
@leniel can you check the question above and give me the module path: `(Get-Module oh-my-posh).ModuleBase`?

**Comment by leniel** [comment]
@JanDeDobbeleer

About your 1st question: I tried to check that on Win 10 (see that I have "Use Unicode UTF-8" check-marked). Let me know if I need to set this somewhere else...

![image](https://user-images.githubusercontent.com/764854/118495343-7d494d80-b6f9-11eb-8c9f-0a055501068e.png)


Result of (Get-Module oh-my-posh).ModuleBase:

![image](https://user-images.githubusercontent.com/764854/118494628-be8d2d80-b6f8-11eb-9b6d-63c2069a0b50.png)

Note: I run Win 10 inside a Parallels Desktop VM. The main\host OS is macOS Catalina 10.15.7.

**Comment by JanDeDobbeleer** [comment]
@leniel I'm pretty sure that path will be the culprit. The good news is I also have parallels set up so I should be able to reproduce this.

**Comment by daedalus-codes** [comment]
Just upgraded myself and came across this same issue (Parallels on macOS 11.3.1) - the module base for me is `\\Mac\Home\Documents\PowerShell\Modules\oh-my-posh\3.150.2`.  

It's nice to see other w/ the same setup.

**Comment by daedalus-codes** [comment]
Okay update!!! I have a shared setting to use all disks with Parallels.  `Y:\` maps to `~` in windows and `Z:\` maps to `/` with this configuration.  

I was able to get the theme to work properly by using the drive letter mapping!!

Update: Downside is this will _not_ work with an elevated prompt as the drive path mapping is only available to the current user and not an elevated Administrator user.  In addition the virtual `\\Mac` isn't as well.  This may be a limitation or intentional on the part of Parallels (Corel Corp).  I ended up copying the file to `~\.oh-my-posh\themes\` folder & changed the entry in `$PROFILE` to use that location instead.

```powershell
Set-PoshPrompt -Theme Y:\Documents\PowerShell\Modules\oh-my-posh\3.150.2\themes\honukai.omp.json
```

Parallels shared configuration:
![Screen Shot 2021-05-17 at 22 42 44](https://user-images.githubusercontent.com/449275/118582668-bae1c100-b761-11eb-8523-86117efbc65d.png)

And now Windows Terminal is back to it's beautiful self w/ Oh My Posh!
![image](https://user-images.githubusercontent.com/449275/118582811-01372000-b762-11eb-86db-dd1cf20aa79c.png)

**Comment by JanDeDobbeleer** [comment]
@leniel the latest version should now display the actual error too.

**Comment by leniel** [comment]
@JanDeDobbeleer just updated and now we can see the error:

![image](https://user-images.githubusercontent.com/764854/118737636-a661ff00-b81b-11eb-9409-614cf9657da9.png)

As you can see, the file does exist here:

![image](https://user-images.githubusercontent.com/764854/118738394-52581a00-b81d-11eb-8f75-7ef04e4b6846.png)

**Comment by JanDeDobbeleer** [comment]
Interesting. It can't open that Powershell path from go, I wonder if removing the Powershell part resolves it.

**Comment by daedalus-codes** [comment]
I'm unfamiliar with go, I've been wanting to learn just haven't gotten around to it :-/ - maybe this would be an applicable time to learn it hehe.

How would one handle Windows network paths like this?  I believe this situation in particular would be mostly unique to Windows VM in Parallels w/ user folder mappings.  On Mac/Linux a network drive would be mounted under `/Volumes/` or `/mnt/` AFAIK so it would appear to be just another path on the system.  

In Parallels, the drive letter mapping could be either `Y:\` or `Z:\` depending if the "All Disks" option is selected.  What's interesting is that `(Get-Module oh-my-posh).ModuleBase` command returns the UNC network path rather than the mapped drive path - maybe that's a bug?

**Comment by leniel** [comment]
@JanDeDobbeleer I did the workaround that @mikhey suggested and passed the full path to the theme with `Set-PoshPrompt`. It worked as expected but now the command line is messy... the caret is not @ the end of the line.

![image](https://user-images.githubusercontent.com/764854/118991601-432ab680-b95a-11eb-8b14-309e7325b146.png)

**Comment by JanDeDobbeleer** [comment]
That's an issue with the first prompt (left one) being too long. Your branch name is rather exotic it seems. We don't have logic in place just yet to see if the right prompt should be hidden based on the current length.

**Comment by JanDeDobbeleer** [comment]
@leniel when inside a directory in the `\\Mac` path, what is the output of `$PWD` and `$PWD.ProviderPath`?

**Comment by leniel** [comment]
@JanDeDobbeleer 

![image](https://user-images.githubusercontent.com/764854/119023712-a9becd00-b978-11eb-8a0c-8d2f87bffc75.png)

**Comment by daedalus-codes** [comment]
Nice work! Thank you!

**Comment by JanDeDobbeleer** [comment]
@leniel I implemented hiding `rprompt` when the current prompt is too large. Can be I need to provide a fix for people using a right aligned block followed by a left aligned one as that could in theory still hide too eager, but not sure if there's anyone out there doing that.

**Comment by abhiverma001** [comment]
when terminal start getting "-bash: oh-my-posh: command not found" then when I run oh-my-posh command in same shell it work 

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/94762544/9bbe9a72-fe31-4ac0-8802-344641ce309e)

**Comment by JanDeDobbeleer** [comment]
@abhiverma001 You're adding the location of oh-my-posh to you PATH after initialization.
