### ISSUE TITLE
Git status not displayed

### ISSUE THREAD

**Issue by skycommand** [JanDeDobbeleer/oh-my-posh#753]
### Prerequisites

- [X] I have read and understand the `CONTRIBUTING` guide
- [X] I looked for duplicate issues before submitting this one

### Description

Hello.

I've just installed oh-my-posh 3.158.3 and I feel most of its themes don't display the Git status properly. (I tried searching this repo's issues, and the only one that came up was #731, which is not relevant enough. So, I'm opening this new issue.)

I initialize my environment with these commands:

```PowerShell
Import-Module -Name "posh-git"
Import-Module -Name "oh-my-posh" -MinimumVersion 3.0
Set-Location F:\Projects\AdminScripts
```

My prompt looks like this:
![`F:\Projects\AdminScripts [master ≡ +1 ~0 -0 !]>`](https://user-images.githubusercontent.com/17097175/119997060-91882700-bfe4-11eb-8628-d11a355f0d04.png)
It says I have one pending change.

So far so good. I continue by setting the `slimfat` theme.

```PowerShell
Set-PoshPrompt -Theme Slimfat
```

My prompt looks like this:
![`Username@Domain > F:\Projects\AdminScripts > master ≡ +1`](https://user-images.githubusercontent.com/17097175/119997698-3dca0d80-bfe5-11eb-9799-85a429dcf292.png)
It says I have one pending change.

Again, so far so good. Here is where the problem starts: I set the `Agnoster` theme.
```PowerShell
Set-PoshPrompt -Theme Agnoster
```

**Actual behavior:** My prompt looks like this:
![Agnoster, with Posh-Git](https://user-images.githubusercontent.com/17097175/119998217-bfba3680-bfe5-11eb-98fb-6199ae8defe1.png)
It says my local repo is in sync with my remote repo, which is not correct.

**Expected behavior:** My prompt must indicate that I have pending changes. Here is how the Agnoster theme from oh-my-posh 2 showed it:
![Agnoster from version 2, with Posh-Git](https://user-images.githubusercontent.com/17097175/119998601-19bafc00-bfe6-11eb-9801-17d7d4601397.png)

### Environment

- **Oh my Posh version:** 3.158.3
- **Theme:** (Several, see explanation)
- **Operating System:** Windows 10 version 21H1 x64
- **Shell:** Windows PowerShell 7.1
- **Terminal:** Windows Terminal 1.8

**Comment by JanDeDobbeleer** [comment]
@skycommand it does not say the remote is in sync, status is disabled for that [config](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/agnoster.omp.json#L36) (it is for [slimfat](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/slimfat.omp.json#L82)). If you want it, [create a custom theme](https://ohmyposh.dev/docs/pwsh#override-the-theme-settings) and [override](https://ohmyposh.dev/docs/git#status) that part in the git segment: `"display_status": true`. The reason is that status can take a significant amount of time in certain repositories severely impacting performance.

**Comment by skycommand** [comment]
@JanDeDobbeleer Okay, I did not expect that at all.

I need to candidly ask you a question: Is there any of the oh-my-posh 2 features that oh-my-posh 3 provides out-of-the-box?

**Comment by JanDeDobbeleer** [comment]
@skycommand do you mean with the standard themes? Because those are made for convenience, not tailored for the actual hardcore user. It's pretty straightforward to create a custom theme you can share/use anywhere and tweak 100% to your liking/use cases. That part is a lot easier compared to V2, which was limited to people understanding Powershell and even then, didn't offer a lot of plug and play.

**Comment by tom-mckinney** [comment]
@JanDeDobbeleer, many of the default templates use the git segment, but only a handful have enabled the status via the `"display_status": true` option. Could we either enable this for the default templates or remove the git segment from any template that does not enable the status? After updating `oh-my-posh` I started seeing only the git SHA in my prompt themes. I believed this to be a bug since this wasn't listed as a breaking change in the release notes.

**Comment by JanDeDobbeleer** [comment]
@tom-mckinney I get your point but we've seen many people having issues with large repos and thus git being slow due to status. What's important to understand, and a key difference when coming from V2, is that the current themes serve more as examples rather than full blown configs to serve every use-case. It's pretty straightforward to create your own enabling every possible feature you'd like and tailoring the experience (which is guaranteed to be compatible). I could've made that change introduce the 4.x version, but we would in all honesty be having the same conversation.

The SHA is another issue to be honest, that would imply `git branch --show-current` doesn't return a value. Can you validate and make sure you're on the latest version of git?

**Comment by tom-mckinney** [comment]
@JanDeDobbeleer, you're absolutely right! I updated git to `2.31.1` and now it's working. Please disregard my previous request—now that it's showing the branch rather than the SHA, the git segment is useful again 😄

Could we update the docs for the git segment to include this requirement?

**Comment by muhammad-usman-anwar** [comment]
@JanDeDobbeleer  having the same issue, status remains same(as below),
![Capture](https://user-images.githubusercontent.com/46624268/120946192-1ac1fb00-c755-11eb-8fde-7f775618f0bd.PNG)
**Sorry had to reupload photo, as I exposed my system info before**

- tested over multiple versions
  - current oh-my-posh version: `3.162.1`
  - git version: `2.31.1.windows.1`
 -  Tested as both PowerShell module and widows app using `winget`
 - Tested in both versions of PowerShell,
   - Packaged PowerShell: `5.1.19041.1023` 
   - PowerShell Core: `7.1.3`

Used to work fine initially(as I installed first 3.149.x), had a custom variation of `paradox` theme. After the first update it stopped working, first I thought it was not compatible with my custom theme so I switched to provided paradox one. Didn't resolved the issue. So I kept on updating versions hoping that would resolve the issue. Now, I did some extensive testing and nothing seems to be working, it may be due to updating the package/module/app or something else

**Comment by JanDeDobbeleer** [comment]
@muhammad-usman-anwar just like the [sample](https://ohmyposh.dev/docs/git#sample-configuration), set `"display_status": true` in your git segment.

**Comment by muhammad-usman-anwar** [comment]
@JanDeDobbeleer thnx

**Comment by DWAK-ATTK** [comment]
I'm sorry for being so dumb, but I too am having the same problem.  The theme was working before updating posh - and now it isn't.  Could you please post the complete instructions for updating the Agnoster theme to include the git status like it was before it was removed?

I've installed posh via the powershell `Install-Module` method.

My complete $PROFILE is:
```
Import-Module oh-my-posh
Set-PoshPrompt -Theme agnosterplus

Import-Module Terminal-Icons
```

Thanks!

**Comment by muhammad-usman-anwar** [comment]
@DWAK-ATTK checkout the documentation https://ohmyposh.dev/docs/git

**Comment by JanDeDobbeleer** [comment]
@DWAK-ATTK you can follow the [guide](https://ohmyposh.dev/docs/installation/customize#adjust-a-theme) to export your current theme and adjust it so it displays the status.

**Comment by gouderhicham** [comment]
if anyone want the repo status to display like it was in v2 you havr to edit 2 files which they are PoshGitTypes and the file of the theme that you are using , in the theme file you gotta use posh git and not git to display the repo status properly 
, im using customized paradox theme and here are the files that you need to change 
__ 1st change the PoshGitPromptSettings class in PoshGitTypes to this : 
`class PoshGitPromptSettings {
    [bool]$AnsiConsole = ($Host.UI.SupportsVirtualTerminal -or ($Env:ConEmuANSI -eq "ON")) -and !$script:GitCygwin
    [bool]$SetEnvColumns = $true

    [PoshGitCellColor]$DefaultColor = [PoshGitCellColor]::new()
    [PoshGitCellColor]$BranchColor  = [PoshGitCellColor]::new([ConsoleColor]::Black)

    [PoshGitCellColor]$IndexColor   = [PoshGitCellColor]::new([ConsoleColor]::Black)
    [PoshGitCellColor]$WorkingColor = [PoshGitCellColor]::new([ConsoleColor]::Black)
    [PoshGitCellColor]$StashColor   = [PoshGitCellColor]::new([ConsoleColor]::Black)
    [PoshGitCellColor]$ErrorColor   = [PoshGitCellColor]::new([ConsoleColor]::Black)

    [PoshGitTextSpan]$PathStatusSeparator      = ' '
    [PoshGitTextSpan]$BeforeStatus             = [PoshGitTextSpan]::new('', [ConsoleColor]::Black)
    [PoshGitTextSpan]$DelimStatus              = [PoshGitTextSpan]::new(' |', [ConsoleColor]::Black)
    [PoshGitTextSpan]$AfterStatus              = [PoshGitTextSpan]::new('', [ConsoleColor]::Black)

    [PoshGitTextSpan]$BeforePath               = [PoshGitTextSpan]::new('', [ConsoleColor]::Black)
    [PoshGitTextSpan]$AfterPath                = [PoshGitTextSpan]::new('', [ConsoleColor]::Yellow)

    [PoshGitTextSpan]$BeforeIndex              = [PoshGitTextSpan]::new('', [ConsoleColor]::Black)
    [PoshGitTextSpan]$BeforeStash              = [PoshGitTextSpan]::new(' (', [ConsoleColor]::Black)
    [PoshGitTextSpan]$AfterStash               = [PoshGitTextSpan]::new(')', [ConsoleColor]::Black)

    [PoshGitTextSpan]$LocalDefaultStatusSymbol = [PoshGitTextSpan]::new('', [ConsoleColor]::Black)
    [PoshGitTextSpan]$LocalWorkingStatusSymbol = [PoshGitTextSpan]::new('?', [ConsoleColor]::Black)
    [PoshGitTextSpan]$LocalStagedStatusSymbol  = [PoshGitTextSpan]::new([char]0x2713, [ConsoleColor]::Black)

    [PoshGitTextSpan]$BranchGoneStatusSymbol           = [PoshGitTextSpan]::new([char]0x00D7, [ConsoleColor]::Black) # × Multiplication sign
    [PoshGitTextSpan]$BranchIdenticalStatusSymbol      = [PoshGitTextSpan]::new([char]0x2261, [ConsoleColor]::Black)     # ≡ Three horizontal lines
    [PoshGitTextSpan]$BranchAheadStatusSymbol          = [PoshGitTextSpan]::new([char]0x2191, [ConsoleColor]::Black)    # ↑ Up arrow
    [PoshGitTextSpan]$BranchBehindStatusSymbol         = [PoshGitTextSpan]::new([char]0x2193, [ConsoleColor]::Black)      # ↓ Down arrow
    [PoshGitTextSpan]$BranchBehindAndAheadStatusSymbol = [PoshGitTextSpan]::new([char]0x2195, [ConsoleColor]::Black)   # ↕ Up & Down arrow

    [BranchBehindAndAheadDisplayOptions]$BranchBehindAndAheadDisplay = [BranchBehindAndAheadDisplayOptions]::Full

    [string]$FileAddedText       = '+'
    [string]$FileModifiedText    = '~'
    [string]$FileRemovedText     = '-'
    [string]$FileConflictedText  = '!'
    [string]$BranchUntrackedText = ''

    [bool]$EnableStashStatus     = $false
    [bool]$ShowStatusWhenZero    = $true
    [bool]$AutoRefreshIndex      = $true

    [UntrackedFilesMode]$UntrackedFilesMode = [UntrackedFilesMode]::Default

    [bool]$EnablePromptStatus    = !$global:GitMissing
    [bool]$EnableFileStatus      = $true

    [Nullable[bool]]$EnableFileStatusFromCache        = $null
    [string[]]$RepositoriesInWhichToDisableFileStatus = @()

    [string]$DescribeStyle = ''
    [psobject]$WindowTitle = {param($GitStatus, [bool]$IsAdmin) "$(if ($IsAdmin) {'Admin: '})$(if ($GitStatus) {"$($GitStatus.RepoName) [$($GitStatus.Branch)]"} else {Get-PromptPath}) - PowerShell $($PSVersionTable.PSVersion.Major).$($PSVersionTable.PSVersion.Minor) $(if ([IntPtr]::Size -eq 4) {'32-bit '})($PID)"}

    [PoshGitTextSpan]$DefaultPromptPrefix       = '$(Get-PromptConnectionInfo -Format "[{1}@{0}]: ")'
    [PoshGitTextSpan]$DefaultPromptPath         = '$(Get-PromptPath)'
    [PoshGitTextSpan]$DefaultPromptBeforeSuffix = ''
    [PoshGitTextSpan]$DefaultPromptDebug        = [PoshGitTextSpan]::new(' [DBG]:', [ConsoleColor]::Magenta)
    [PoshGitTextSpan]$DefaultPromptSuffix       = '$(">" * ($nestedPromptLevel + 1)) '

    [bool]$DefaultPromptAbbreviateHomeDirectory = ($PSVersionTable.PSVersion.Major -gt 5) -and !$IsWindows
    [bool]$DefaultPromptAbbreviateGitDirectory  = $false
    [bool]$DefaultPromptWriteStatusFirst        = $false
    [bool]$DefaultPromptEnableTiming            = $false
    [PoshGitTextSpan]$DefaultPromptTimingFormat = ' {0}ms'

    [int]$BranchNameLimit = 0
    [string]$TruncatedBranchSuffix = '...'

    [bool]$Debug = $false
}`
and 2nd : im using paradox theme so here is the code to get powershell like the above : 
`{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "type": "prompt",
      "alignment": "left",
      "newline": true,
      "segments": [
        {
          "type": "root",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#100e23",
          "background": "#ffe9aa"
        },

        {
          "type": "path",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#100e23",

          "background": "#0196fb",
          "properties": {
            "folder_icon": "\u2122",
            "folder_separator_icon": " \uE0B1 ",
            "style": "full"
          }
        },
        {
          "type": "poshgit",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#000000",
          "background": "#ffbb02"
        }
      ]
    },
    {
      "type": "prompt",
      "alignment": "left",
      "newline": true,
      "segments": [
        
        {
          "type": "text",
          "style": "powerline",
          "foreground": "#007ACC",
          "properties": {
            "prefix": "",
            "text": "\u276F"
          }
        }
      ]
    }
  ],
  "final_space": true
}`

**Comment by aral** [comment]
@JanDeDobbeleer Just a quick heads up that both your link and @muhammad-usman-anwar’s are currently 404.

**Comment by JanDeDobbeleer** [comment]
@aral you can find that guide [here](https://ohmyposh.dev/docs/installation/customize#adjust-a-theme) now. Also updated above.

**Comment by aral** [comment]
Thanks @JanDeDobbeleer. Figured it out yesterday based in another of your replies but just wanted to give a heads up about the docs site being down. Take care + hope you’re having a good week so far.
