### ISSUE TITLE
Export-PoshTheme crash on path

### ISSUE THREAD

**Issue by tonybaloney** [JanDeDobbeleer/oh-my-posh#768]
The example in the documentation to export a theme to configure it isn't working:

```default
> Export-PoshTheme -FilePath ~/.mytheme.omp.json -Format json
Cannot find an overload for "GetFullPath" and the argument count: "2".
At line:156 char:9
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
```

This is the latest version of oh-my-posh, I just ran the update before this command.

**Comment by lnu** [comment]
The issue is with powershell <=5.1. A change has been done to fix a bug(https://github.com/JanDeDobbeleer/oh-my-posh/issues/748) with relative path, but it works well in powershell core and not in powershell. We'll have to find another way round.   
In the meantime: if you don't specify a FilePath the theme is copied to the clipboard.
