### ISSUE TITLE
Wrong home directory when using MSYS2

### ISSUE THREAD

**Issue by macaquinyho** [JanDeDobbeleer/oh-my-posh#786]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

The wrong home directory gets displayed when using MSYS2

### Environment

- Oh My Posh version: 3.162.1 installed with scoop
- Theme: Any
- Operating System: Windows 10
- Shell: Bash on MSYS2
- Terminal: Windows Terminal

#### Optional

- posh-git version:
- git version: 2.31.1.windows.1

### Steps to Reproduce

1. Launch the oh-my-posh executable inside an MSYS2 bash shell.

**Expected behavior:** The home directory should be $HOME,

**Actual behavior:**  Instead of $HOME it's the $USERPROFILE (the Windows home directory, not the msys2 home dir)
![imatge](https://user-images.githubusercontent.com/14185777/120937091-c47c9a00-c70b-11eb-9ae8-616879d09f99.png)

**Comment by JanDeDobbeleer** [comment]
@Toomoch ah yes. Probably because it's the Windows binary which (obviously) reports the Windows home. Let's see if we can favor the variable over asking go what it is.

Unrelated, but still I have to ask out of personal curiosity. Why do you bother with MSYS2 when you've got WSL2?

EDIT: we can simply adjust the following code to first listen to the `$HOME` variable rather then default to `$USERPROFILE`.

**Comment by macaquinyho** [comment]
> 
> 
> @Toomoch ah yes. Probably because it's the Windows binary which (obviously) reports the Windows home. Let's see if we can favor the variable over asking go what it is.
> 
> Unrelated, but still I have to ask out of personal curiosity. Why do you bother with MSYS2 when you've got WSL2?
> 
> EDIT: we can simply adjust the following code to first listen to the `$HOME` variable rather then default to `$USERPROFILE`.

I use MSYS2 as well as WSL2, it's just that with MSYS2 I can work on native windows stuff. 
Thanks for the insight.
