### ISSUE TITLE
[Question] how to make my config persistent 

### ISSUE THREAD

**Issue by saostad** [JanDeDobbeleer/oh-my-posh#825]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description
I have an entry level question.
I have activated a theme and it's great but after I close the terminal and reopen it, it's gone and I have to reactivate the theme, how can I my config persistent.
I already read the docs but couldn't find anything related.

### Environment

- Oh My Posh version:
- Theme: jandedobbeleer
- Operating System: Win10 x64
- Shell: Powershell 7.1.3
- Terminal: Windows Terminal

**Comment by JanDeDobbeleer** [comment]
@saostad when using Powershell, you can add those lines to your `$PROFILE`. Powershell loads that file a startup, so adding the following lines there and saving the file will load it again when restarting Powershell.

```powershell
Import-Module oh-my-posh
Set-PoshPrompt -Theme jandedobbeleer
```

While this is [mentioned](https://ohmyposh.dev/docs/pwsh#replace-your-existing-prompt) in the docs, I understand this can be confusing when you're not familiar with Powershell. You can read up on profiles [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles).

**Comment by saostad** [comment]
thanks, it's working now 🎉🎉🎉🎉

**Comment by BoisonChang** [comment]
> @saostad when using Powershell, you can add those lines to your `$PROFILE`. Powershell loads that file a startup, so adding the following lines there and saving the file will load it again when restarting Powershell.
> 
> ```powershell
> Import-Module oh-my-posh
> Set-PoshPrompt -Theme jandedobbeleer
> ```
> 
> While this is [mentioned](https://ohmyposh.dev/docs/pwsh#replace-your-existing-prompt) in the docs, I understand this can be confusing when you're not familiar with Powershell. You can read up on profiles [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles).


**I follow instruction show  [docs page](https://ohmyposh.dev/docs/migrating) in terminal :**



## and then two question happen:
### 1 why this [docs page](https://ohmyposh.dev/docs/migrating) recommend Delete the import of the PowerShell module in your $PROFILE?

### 2 after finishing the Migration steps in  [docs page](https://ohmyposh.dev/docs/migrating) , terminal can't read "import oh-my-posh" written in   `$PROFILE`.



> like that:



Import-Module : The specified module 'oh-my-posh' was not loaded because no valid module file was found in any module directory.
At C:\Users\Boison Chang\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:2 char:1
+ Import-Module oh-my-posh
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (oh-my-posh:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
 
Set-PoshPrompt : The term 'Set-PoshPrompt' is not recognized as the name of a cmdlet, function, script file, or operable program. Check t
he spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\Boison Chang\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:3 char:1
+ Set-PoshPrompt -Theme paradox
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-PoshPrompt:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by JanDeDobbeleer** [comment]
@saostad please follow every step in that page. Read it again, carefully, and execute every command/step listed. That way your prompt will work correctly.

**Comment by BoisonChang** [comment]
> @saostad please follow every step in that page. Read it again, carefully, and execute every command/step listed. That way your prompt will work correctly.

OK, Thank you. I will try carefully again.
