### ISSUE TITLE
oh-my-posh cli unable to print current config " open : The system cannot find the file specified"

### ISSUE THREAD

**Issue by vishu42** [JanDeDobbeleer/oh-my-posh#826]
### Prerequisites

- [ yes] I have read and understand the `CONTRIBUTING` guide
- [yes ] I looked for duplicate issues before submitting this one

### Description

I get the following error when i run `oh-my-posh -print-config`. I had setup the config by providing the `-config` flag like so `oh-my-posh -config "C:\Users\vishal\oh-my-posh.json"`
``` 
C:\Users\vishal> oh-my-posh.exe -print-config
Oh My Posh Error:
 open : The system cannot find the file specified.
INVALID CONFIG:
```
the `oh-my-posh.json` file
```
{
    "final_space": true,
    "blocks": [
      {
        "type": "prompt",
        "alignment": "left",
        "segments": [
          {
            "type": "kubectl",
            "style": "powerline",
            "powerline_symbol": "\uE0B0",
            "foreground": "#000000",
            "background": "#ebcc34",
            "properties": {
              "prefix": " \uFD31 ",
              "template": "{{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}"
            }
          }
        ]
      }
    ]
  }
```

open : The system cannot find the file specified.

### Environment

- Oh My Posh version: 3.166.3
- Theme: No theme specified (using the default one)
- Operating System: Windows 10 Pro (os build - 19042.1052)
- Shell: PowerShell
- Terminal: windows terminal

#### Optional

- posh-git version:
- git version:

### Steps to Reproduce

1. Install the oh-my-posh installer from releases and install it. 
2. Run the command `oh-my-posh -config "C:\Users\vishal\oh-my-posh.json"`
3. Run `oh-my-posh.exe -print-config` 

**Expected behavior:** Its supposed to print the config. 

**Actual behavior:** It throws error.

**Comment by lnu** [comment]
`-print-config` takes the config path in parameter, otherwise you get the error you shared us => https://ohmyposh.dev/docs/windows#override-the-theme-settings
If you want to export the current config to the clipboard, you can do it in powershell with Export-PoshTheme but not in other shells.
Or you can also call `oh-my-posh.exe -print-config -config="$($PoshSettings.Theme)" ` to print the current config

**Comment by JanDeDobbeleer** [comment]
@vishu42 as @lnu already stated, this is expected behaviour. You need to use the helper functions in the shells as the theme as cached there rather than from an executable perspective. You can find the helper functions per shell in the [docs](https://ohmyposh.dev/docs/windows#override-the-theme-settings).
