### ISSUE TITLE
Transient prompt does not behave correctly when the prompt is too long

### ISSUE THREAD

**Issue by Ash258** [JanDeDobbeleer/oh-my-posh#840]
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] I have looked for duplicate issues before submitting this one

### Description

[Description of the bug or feature]

When the prompt overflow to second line, then only the second line is removed in when transient prompt is enabled.

![A](https://i.imgur.com/KyKRpTG.gif)

### Environment

- Oh My Posh version: 3.168.0
- Theme: https://github.com/Ash258/Scoop-Ash258/blob/main/support/oh-my-posh/Ash258.json
- Operating System: Windows 10 20H2 19042.1081
- Shell: Powershell 7.2.0-preview.7
- Terminal: Windows Terminal 1.7.210226002-release1.7

#### Optional

- posh-git version:  1.0.0
- git version:  2.32.0.windows.1

### Steps to Reproduce

1. Open terminal with profile, which have Path segment
2. Go to really long path or lower the terminal width
3. Type some command

**Expected behavior:** [What you expected to happen]

![image](https://user-images.githubusercontent.com/13260377/124498266-584d8e80-ddbc-11eb-9604-d9ff49eaaf8d.png)

**Actual behavior:** [What actually happened]

![image](https://user-images.githubusercontent.com/13260377/124498291-64395080-ddbc-11eb-89b0-d9294a5e4648.png)

**Comment by JanDeDobbeleer** [comment]
@Ash258 ah yes, that hasn't been taken into account. I'm also not even sure how to detect this.

**Comment by JanDeDobbeleer** [comment]
@Ash258 I did a bit of digging and doing this on Powershell is a challenge. There is a [function](https://docs.microsoft.com/en-us/dotnet/api/microsoft.powershell.psconsolereadline.invokeprompt?view=powershellsdk-1.1.0#Microsoft_PowerShell_PSConsoleReadLine_InvokePrompt_System_Nullable_System_ConsoleKeyInfo__System_Object_) you can use out of the box to redraw the prompt but that one doesn't work when you're multiline (which is a bug imho, it should redraw from the start, rather than the line of the cursor). That's why we have a custom implementation that takes all of this into account (which is also rather challenging as there are many edge cases to consider). And when it comes to this specific issue, there's no line break, it's simply rendered like that by the console host...

**Comment by JanDeDobbeleer** [comment]
@Ash258 progress, seems like setting `Set-PSReadlineOption -ExtraPromptLineCount 1` fixes that. I can also make that dynamic. Will push a change.

**Comment by JanDeDobbeleer** [comment]
@Ash258 can you try again with the latest version? If this doesn't work I'll need to find another way 😄

**Comment by JanDeDobbeleer** [comment]
@Ash258 OK, so an update on my end. I tried a lot of things, looked at many, many posts regarding how terminals handle line wrapping and that's where I found out this isn't a configuration/support that's needed from oh-my-posh's perspective but rather a terminal setting. I can enable `tput rmam` to disable word wrap in iTerm for example, making it render as you want it and not having the need for any crazy logic when it comes to this in oh-my-posh (believe me, this is really hard thing to do and there are 0 guarantees as the terminal wrap setting can even break this). Feel free to follow the [issue](https://github.com/microsoft/terminal/issues/1860) at Windows Terminal to get that functionality ;-)
