### ISSUE TITLE
ls.exe from mingw will cause write error

### ISSUE THREAD

**Issue by leovincentseles** [JanDeDobbeleer/oh-my-posh#853]
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] I have looked for duplicate issues before submitting this one

### Description

I download [Mingw](https://sourceforge.net/projects/mingw/files/Installer/mingw-get-setup.exe/download) and install the msys-base in the Base Setup. Use the ls.exe provided by the cygwin, and want to see the exact chinese subdirectory name.

Use the default powershell. The command `ls.exe --show-control-chars` can list the directory well.
After executing `Import-Module oh-my-posh`, then `ls.exe --show-control-chars`  will report `write error`

### Environment

- Oh My Posh version: 3.168.3
- Theme: None
- Operating System: Windows 10 1909 (build 18363.418)
- Shell: Powershell
- Terminal: Windows Terminal

### Steps to Reproduce
[test.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/6819700/test.zip)

1. Extract the provided `test.zip`, and open a windows terminal under the test directory.
2. `Set-PSReadLineOption -Colors @{"Parameter"="#ff81f7"}` just for highlight the parameter.
3. The `dir` command show the filename correctly.
4. `.\ls.exe` show the incorrect filename.
5. So use `.\ls.exe --show-control-chars`, and see the correct filename
6. `Import-Module oh-my-posh`
7. `.\ls.exe --show-control-chars` will encounter the write error message.

![image](https://user-images.githubusercontent.com/36748589/125712621-2995d790-76ae-4915-a40c-6e45d1f24c6a.png)

**Comment by JanDeDobbeleer** [comment]
This is because we force the terminal to UTF8 and that executable for some reason can't handle that. I would either use a modern tool like [exa](https://github.com/ogham/exa), or force your terminal back to the encoding it is in by default BUT that can obviously also break oh-my-posh. We're not removing that setting as powershell will adopt that by default going forward anyways.

Check encoding without oh-my-posh imported:

```pwsh
[console]::OutputEncoding
```

Set to that encoding after importing oh-my-posh:

```pwsh
[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.MyEncoding
```

This obviously voids your warranty 😄
