### ISSUE TITLE
Error while running . $PROFILE to make changes

### ISSUE THREAD

**Issue by advrxh** [JanDeDobbeleer/oh-my-posh#899]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When I set a theme and run 
```powershell
. $PROFILE
```
to save the prompt it returns me this error. can someone help me!
![image](https://user-images.githubusercontent.com/72086030/129468770-4da19129-8a36-4ed9-95f4-e7d6dae2865a.png)

```powershell
. : The term 'C:\Users\Admin\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:3
+ . $PROFILE
+   ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Admin\...ell_profile.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Version

latest version..

### Theme

stelbent.minimal

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Relevant log output

```shell
. : The term 'C:\Users\Admin\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:3
+ . $PROFILE
+   ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Admin\...ell_profile.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by JanDeDobbeleer** [comment]
The only thing this does is reload you profile. If for some reason that command doesn't work, you can always restart you shell/terminal.

The reason this doesn't work is because the file doesn't exist yet, the docs state you have to add the `Import-Module oh-my-posh` line and others to that file, but it looks like you're running those commands directly in the shell. Using any editor to create and edit that file will also make `. $PROFILE` work.
