### ISSUE TITLE
Not working with GitHub CLI

### ISSUE THREAD

**Issue by codeprefect** [JanDeDobbeleer/oh-my-posh#944]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When you use Github CLI, It throws this error whenever you press the navigation button.
NOTE: issue does not occur on bash

See attached screenshot
<img width="1189" alt="Screenshot 2021-09-11 at 00 35 50" src="https://user-images.githubusercontent.com/44836329/132927855-58cf1559-b745-42c6-9bb1-80fe72b6c5d2.png">

### Version

3.180.1

### Theme

jandedobbeleer.omp.json

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

zsh, bash, powershell

### Relevant log output

```shell
could not collect title and/or body: unable to confirm: could not prompt: Unexpected Escape Sequence: ['\x1b' 'O']
```

**Comment by JanDeDobbeleer** [comment]
@mimam419 this is not an issue with oh-my-posh but rather the gh CLI. They have an [issue](https://github.com/cli/cli/issues/544) for this. Searching Google for this also returns quite a bit of results which indicate the terminal can be the root cause, but highly unlikely not oh-my-posh. My setup is similar: macOS and iTerm2 and I don't see this with the gh CLI.
